INSERT INTO public._nc_staging VALUES
('2025-09-11', 'P-Sup4', 'en_cours', 'Nommage Projet dans "07 PROJET"', 'KEON', NULL, 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', NULL, 'certains projets ne sont pas nommer correctement', NULL, NULL, 'Faire communication interne au service commercial', 'prendre le temps de nommer les projets correctement', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'francois.haumont@keon-group.com'),
('2025-09-24', 'P-Op6', 'en_cours', 'Saisi QADRO août à compléter', 'CERES', 'CERES', 'nc_qualite', 'ACHAT', NULL, '2 saisies dans QADRO en août le 28/08 sans nom de gisement, de transporteur et de négociant', 'oui', 'Saisie non effectuée le jour même ou le lendemain', 'Saisir à réception des camions et télécharger les documents le jour même ou le lendemain matin', 'Vérifier tous les vendredis ou lundis matin s''il manque des saisies ou des documents. Comprendre pourquoi la coche "document" dans QADRO peut-être verte alors qu''il manque TP ou LV', NULL, NULL, 'anne.rivron@teikei.fr', 'Alexandre.Piton@keon-group.com'),
('2025-09-25', 'P-Sup2', 'en_cours', 'suivi de la check list du On boarding', 'KEON', NULL, 'points_vigilance', 'RH GROUPE', NULL, 'absence de suivi des taches et formations à réaliser', NULL, NULL, NULL, 'Faire un point avec louis pour mettre en place un suivi des formations.
A rajouter dans le CR de point sur la période d''essai', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-09-26', 'P-Op3', 'en_cours', 'Outil de gestion de projet', 'NASKEO', NULL, 'axe_amelioration', 'BUREAU D''ETUDES MOE/ETD', NULL, 'Nous avons besoin d''un outil de gestion de projet global permettant d''avoir la vue sur l''avancement du projet du début à la fin (dimensionnement, PC/ICPE, lancement MOE, recours, etc).', 'non_concerne', 'Manque de traçabilité de l''information.', NULL, 'Echanges et travail la création d''un outil de suivi de projet avec le service IT', NULL, NULL, 'marion.pavat@naskeo.com', 'marion.pavat@naskeo.com'),
('2025-10-02', 'P-Sup3', 'en_cours', 'Intégrer un processus Communication externe', 'KEON', '2025', 'axe_amelioration', 'COMMUNICATION - MARKETING', 'Audit interne ISO', 'Manque ce processus pour savoir comment maitriser la communication externe (exemple départ d''Aurélien)', NULL, NULL, NULL, 'Ecrire le processus', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'claire.sassias@keon-group.com'),
('2025-10-02', 'P-Op5', 'en_cours', 'Outil de suivi', 'TEIKEI', '2025', 'axe_amelioration', 'APPROVISIONNEMENT', 'Audit interne ISO', 'Utilisation d''un fichier excel actuellement.', NULL, NULL, NULL, 'Passer sur un logiciel de gestion des flux', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'gwenaelle.jacq@teikei.fr'),
('2025-10-02', 'P-Op1', 'en_cours', 'Remplissage du CRM', 'NASKEO', '2025', 'axe_amelioration', 'COMMERCE', 'Audit interne ISO', 'certaines informations ne sont pas rentrées dans le CRM', NULL, NULL, NULL, 'insister et communiquer sur l''importance du CRM pour la qualification', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'germain.lheriau@naskeo.com'),
('2025-10-02', 'P-Op1', 'en_cours', 'Analyser les  affaires gagnées', 'NASKEO', '2025', 'axe_amelioration', 'COMMERCE', 'Audit interne ISO', 'les risques sont analysés vi les affaires perdues mais pas les opportunités gagnées', NULL, 'An,alyse Post Morten devrait intégrer les affaires gagnées pour pérenniser les FCS et pas uniquement les affaires perdues', NULL, 'prévoir une analyse des affaires gagnées à inclure dans le CRM', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'germain.lheriau@naskeo.com'),
('2025-10-02', 'P-Op4', 'en_cours', 'indicateurs chiffrés', 'NASKEO', '2025', 'axe_amelioration', 'CONSTRUCTION', 'Audit interne ISO', 'les indicateurs suivis ne sont pas chiffrées', NULL, NULL, NULL, 'travailler sur une manière de trouver un indicateur chiffré', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'nicolas.kocet@naskeo.com'),
('2025-10-07', 'P-Op2', 'en_cours', 'Suivi des risques', 'TERGREEN', '2025', 'axe_amelioration', 'DEVELOPPEMENT', 'Audit interne ISO', 'Le suivi des risques opportunités dans les développements de projets demandent à être mieux démontré.', NULL, NULL, NULL, 'mettre en place un suivi', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'sophie.clermont@ter-green.com'),
('2025-10-07', 'P-Op2', 'en_cours', 'REX rapport d''activité', 'TERGREEN', '2025', 'axe_amelioration', 'DEVELOPPEMENT', 'Audit interne ISO', 'L’utilisation du REX du rapport d’activité sur de nouveaux développements à venir pourrait être mieux utilisé.', NULL, NULL, NULL, 'améliorer l''utilisation du REX', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'sophie.clermont@ter-green.com'),
('2025-10-07', 'P-Sup2', 'en_cours', 'Enregistrement formation intégration', 'KEON', '2025', 'axe_amelioration', 'RH', 'Audit interne ISO', 'Les formations internes intégration et qualité demandent à être enregistrées', NULL, NULL, NULL, 'enregistrer les formations réaliser par collaborateur 
Creer un QUIZ de vérification des informations transmises', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-10-07', 'P-Sup2', 'en_cours', 'formation recyclage non à jour', 'KEON', '2025', 'axe_amelioration', 'RH', 'Audit interne ISO', 'La liste des formations de recyclage demande à être mise à jour', NULL, NULL, NULL, 'formaliser la mise à jour
Nettoyer la base de données', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-10-13', 'P-Op5', 'en_cours', 'Road map Teikei', 'TEIKEI', NULL, 'axe_amelioration', 'APPROVISIONNEMENT', NULL, 'Travail dans l''urgence . bcp de gestion par téléphone. manque de traçabilité et de formalisation des actions', NULL, NULL, NULL, 'créer une raod map Teikei  ( Todo list)  pour lister les actions a faire quand l''ambiance de travail est plus calme!', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'anne.rivron@teikei.fr'),
('2025-10-31', 'P-Sup4', 'en_cours', 'désynchronisation par erreur des BAL archivée = perte définitive des anciennes boites mail
Uniquement 30j de sauvegarde sur les archives et découverte par hasard en cherchant une BAL d''archives', 'KEON', 'KEON', 'nc_qualite', 'SERVICES GENERAUX', NULL, 'désynchronisation par erreur des BAL archivée = perte définitive des anciennes boites mail
Uniquement 30j de sauvegarde sur les archives et découverte par hasard en cherchant une BAL d''archives
', 'non', 'Problème de formation sur ce suejt
Problème de procédure qui n''impose pas une validation en cas de modif du paramétrage des sauvegardes', 'Pas d''action correctives possibles sur les data perdues
', 'Etudes si sauvegardes possibles via VEEAM
Ajout d''une procédure qui n''impose pas une validation en cas de modif du paramétrage des sauvegardes', NULL, NULL, 'valentin.bertrand@sycomore-services.com', 'bruno.lucas@naskeo.com'),
('2025-11-02', 'P-Op6', 'en_cours', 'Non respect du planning d''apport (Méthamix prévu le 24/11 livré le 25/11).', 'TEIKEI', 'CERE', 'nc_fournisseur', 'EXPLOITATION', 'ROE', 'Réserve de Méthamix vide au 24/11 et pas de livraison. Problème d''alimentation du méthaniseur.', NULL, 'Dépendance au site producteur pour les chargements. ', NULL, 'Retour fournisseur sur non conformité
Prévision d''envoi d''un mail à l''ensemble des fournisseurs pour rappel des consignes et de la prévenance à effectuer ', NULL, NULL, 'teresa.nicolle@keon-spv.com', 'Alane.laureillard@teikei.fr'),
('2025-11-27', 'P-Op5', 'en_cours', 'Catégoriser le déchet sur Qadro', 'SYCOMORE', '2025', 'axe_amelioration', 'APPROVISIONNEMENT', 'ISO 9001', 'absence du la catégorie du déchet sur Qadro', NULL, 'au lieu de mettre la durabilité qui sera toujours à 100%, il serait intéréssant de mettre la catégorie "circulaire, bio sourcé, Waste résidu,...)', NULL, 'modifier les champs de remplissage de Qadro', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'gwenaelle.jacq@teikei.fr'),
('2026-01-07', 'P-Sup4', 'en_cours', 'PB DE DROITS DROITS D ''ACCES', 'KEON', 'KEON', 'nc_qualite', 'SERVEUR-INFORMATIQUE-WEB', NULL, 'Acces au dossier RH de la part de 2 collaborateurs non habilité. Information remontée par la directrice administratif et financière', 'oui', 'PB DANS L''ATTRIBUTION DES DROITS D''ACCES A L''ARRIVEE ET A LA MUTATION D''UN SALARIE', 'AUDIT COMPLET DE LA MATRICE DES DROITS', 'METTRE EN PLACE UN AUDIT REGULIER DE LA MATRICE ET DE SON APPLICATION', NULL, NULL, 'valentin.bertrand@sycomore-services.com', 'valentin.bertrand@sycomore-services.com'),
('2026-04-22', 'P-Op5', 'en_cours', 'réception de Stator Vogelsang non conforme', 'SYCOMORE', 'PSTOC', 'nc_fournisseur', 'PIECES', 'vogelsang', 'réception de Stator Vogelsang non conforme (PKE0029) x3', 'non', 'manque de vigilance du fournisseur', 'relancer fournisseur pour enlèvement des pièces non conformes et livraison des pièces conformes', 's''entretenir avec notre fournisseur sur nos différents problèmes', NULL, NULL, 'Paul.Lapeyre@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2024-03-01', 'P-Op1', 'cloturee', 'Oubli de vente d''un mètre de bardage', 'NASKEO', 'GIRO', 'nc_qualite', 'COMMERCE', NULL, 'Le service commercial a oublié de vendre 1 m supplémentaire de bardage au client à la suite de la modification d''implantation des cuves. Nous nous retrouvons donc dans une situations où nous construisons une cuve de 8m de haut enterrée de 1m donc avec 7m à couvrir avec du bardage. Or, il n''y a que 6m de bardage de vendu. Cela occasionne un trou de budget d''environ 13k€.', 'ne_sais_pas', 'Manque de prise en compte des modifications d''implantation des cuves par le service commercial', '1- Insister sur la Communication étroite entre le bureau d''études qui définit l''implantation des cuves et le service commercial qui vend les prestations', 'ASAP pour éviter ce genre d''erreur sur les futurs chantiers', NULL, NULL, 'kevin.bouvron@naskeo.com', NULL),
('2023-11-06', 'P-Op2', 'cloturee', 'Surcoût de 4M€ soit 15% des CAPEX', 'TERGREEN', 'ABEV', 'nc_qualite', 'DEVELOPPEMENT', NULL, 'Environ 1 an après le démarrage du chantier et alors que le projet avait déjà été financé, nous avons constaté un surcoût  de capex de 4M€ soit environ 15% de l''enveloppe initiale. 
Les 4M€ sont répartis selon les postes suivants: 1,4M€ liés au chantier, 1M€ liés à un changement de stratégie (achat de matériel de transport), 1M€ de BFR en plus, 600k€de frais bancaires en plus liés à une sous-estimation initiale + au retard du chantier qui a entrainé un report de 6 mois de la date de consolidation et donc une augmentation des intérêts intercalaires', 'oui', '1. Surcoût chantier : lié à l''incompétence de la MOE / lié plus à un problème de personne qu''à la société en charge de la MOE /  l''entreprise n''a pas bien suivi le travail de son personnel / Surcoût dus à des problématiques d''interfaces + de suivi de chantier // TG avait identifié une partie des surcoûts mais a considéré que le projet devait avancer malgré tout puisqu''il y avait notamment des impacts sur NSK qui avait démarré le chantier avant l''entrée de TG 
2. BFR : besoin de financer une récolte de Cive supplémentaire + payer les salaires du personnel 6 mois de plus -->  le besoin supplémentaire est essentiellement dû au retard du chantier --> cf pb MOE
3. Matériel  : lié à une recherche d''optimisation des OPEX
4. Financement : lié au retard + sous-estimation des intérêts

RQ : concernant le retard, on savait dès la signature du bancaire que la date de conso était trop proche vue l''ampleur du projet', 'Actions déjà réalisées pour le projet:
1- Changement du MOE
2- Mise en place d''un suivi du budget
3- Demande de waiver bancaire + appel de fonds des associés

Actions générales déjà réalisées:
4- Master suivi de budget qui permet de recalculer les intérêts bancaires en fonction des besoins de tirage', 'Pour les projets GL:
1- Mettre en place des audits techniques si le MOE n''est pas NSK à faire réaliser par NSK / notamment sur les CDC et les interfaces entre les lots
2- Rencontrer la MOE, demander ses références, lui expliciter les enjeux et contraintes du projet
3- Challenger le temps qu''elle a prévu de consacrer au projet

Pour tous les projets:
4- Exiger un reporting budget à date + en phase chantier de la MOE + MOA mensuelle --> modification du pacte d''associé
5- TG doit proposer systématiquement son outil de suivi', NULL, NULL, 'alain.baraton@keon-group.com', 'sophie.clermont@ter-green.com'),
('2024-09-10', 'P-Op5', 'cloturee', 'livraison client', 'SYCOMORE', 'SURG', 'nc_qualite', 'PIECES', NULL, 'INVERSION PRODUIT', 'non', 'PREPARATION DANS LA PRECIPITATION
INVERSION PRODUIT
NON CONTROLE AVANT EXPEDITION', '1- ECHANGE DES PIECES PAR UN TECHNICIEN LORS DE L INTERVENTION ( PASSE AU STOCK EN AMONT)', 'EMBAUCHE =  plus de bande passante', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2023-11-24', 'P-Sup4', 'cloturee', 'Attaque du site WEB', 'KEON', 'KEON', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1- monter en comptence en interne pour mapper nos systèmes non hébergé sur site. (identifier un prestatire pour nous former)
2- rédiger le Cahier des charge complet pour les prestataires', NULL, NULL, 'patrick.foltzenlogel@keon-group.com', NULL),
('2024-07-12', 'P-Op4', 'cloturee', 'NCm5 - Absence du mode opératoire pour l''identification des AP-AU', 'NASKEO', '2024', 'nc_qualite', 'EXECUTION', 'QUALIMETHA', 'Il manque le mode opératoire
G2 - Modèle d’identification des arrêts et coupures d’urgences avec information sur les coupures provoquées', 'oui', 'La détermination des AU-AP est fait par expérience, elle n''est pas formaliser par une analyse', '1- Réalisation les analyses fonctionnelles permettront la description du fonctionnement des AU/AF.', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'simon.bigot@naskeo.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCM1 - Absence déclaration CE sur l''ensemble de l''installation', 'NASKEO', '2024', 'nc_qualite', 'CONSTRUCTION', 'QUALIMETHA', 'Il n’existe pas de déclaration CE sur l’ensemble de l’installation.
D4 - Respect de la Directive Machine', 'oui', 'Engagement fort de Nsk de certifier CE toute l''installation.', '1- Se réunir pour échanger sur la NCm', '1- Mise en place d’une analyse  de dangers systématique 
2- Réalisation procédure pour délivrance du certificat CE
3- Réalisation master analyse fonctionnelle par CH4 process avec NSk
4- Réalisation trame analyse de risque.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'betty.walheim@naskeo.com'),
('2023-02-07', 'P-Sup5', 'cloturee', 'Création fiche fournisseurs Divalto', 'KEON', 'KEON', 'nc_qualite', 'COMPATIBILITE', NULL, 'Lors de la création des fiches fournisseurs aucune information sur les délais de paiement transmis', 'oui', 'Non utilisation du tableau mis en place et non transmis au fournisseur afin que les acheteurs transmettent les infos plus rapidement au service compta en donnant que le lien société.com', '1- Remettre en place le tableau ou transmettre cette donnée de délai de paiement dans le corps du mail mais le service compta ne doit pas traiter le devis envoyé.', '1- Communiquer sur la nouvelle procédure

les acheteurs prennent en compte que le délai de paiement est important lors de l''acceptation du devis et mettre une politique commune au groupe soit un paiement à 30 ou 45 jours. et transmettre cette donnée au service compta dans le corps du mail.', NULL, NULL, 'corinne.beutier@keon-group.com', 'alexandre.baffou@naskeo.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCm6 - Absence du suivi des levées des réserves', 'NASKEO', '2024', 'nc_qualite', 'CONSTRUCTION', 'QUALIMETHA', 'Il manque le suivi des levées de réserves du CAT et signature par le client de ces levées des réserves.
les PV de réception définitive par contre sont signés sans réserve
K8 - Outil de suivi et gestion des non-conformités pour les projets', 'oui', 'Réalisation du PV de levée des Réserves du CAT.', '1- Réalisation du CAT => avec réserves le cas échéant
2- Réalisation et suivi des réserves via un PV de levée', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'nicolas.kocet@naskeo.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCm4 - Absence du tableau de synthèse des chaines de sécurité', 'NASKEO', '2024', 'nc_qualite', 'EXECUTION', 'QUALIMETHA', 'Il manque le tableau de synthèse des chaînes de sécurité pour l''exploitation.
E16 - Dossier des Ouvrages Exécutés (DOE) au sein de la notice d’instructions', 'oui', 'Les chaines de sécurité sont vérifiées lors de la mise en service. Mais pas de CR formilisé', '1- Le tableau de synthèse des chaines de sécurité sera exporté et transmis à l’exploitant', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'christophe.lhote@naskeo.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCm3 - Absence de formalisation de la vérification de l''identification des équipements', 'NASKEO', '2024', 'nc_qualite', 'MISE EN SERVICE', 'QUALIMETHA', 'La vérification du marquage de la tuyauterie réalisée et apparaît dans le CR interne, mais n''est pas formalisé dans l''organisation projet.
E15 - Identification des équipements', 'oui', 'A intégrer à la procédure de mise en service', '1- Réalisation de la Procédure Réception/marquage des équipements
2- Check list a ingérer à l''AMS ( Voir avec CLH)', '1- Identification des équipements sur leur câblage au niveau de la boite à borne + a coté de la plaque moteur', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'nicolas.kocet@naskeo.com'),
('2024-07-12', 'P-Op1', 'cloturee', 'NCm2 - Absence d''information sur le risque lié aux intrants dans l''offre', 'NASKEO', '2024', 'nc_qualite', 'COMMERCE', 'QUALIMETHA', 'L''information n''est pas présente dans l''offre
E11 - Evaluation et gestion des risques liés aux intrants', 'oui', 'Information pouvant faire peur au stade de l''offre', '1- Réalisation d’une annexe décrivant les principaux risques liés au intrants c’est-à-dire le pH, odeur, moussage,…', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'germain.lheriau@naskeo.com'),
('2024-07-12', 'P-Op1', 'cloturee', 'NCM3 - Absence du zonage ATEX dans l''offre', 'NASKEO', '2024', 'nc_qualite', 'COMMERCE', 'QUALIMETHA', 'Il manque le zonage ATEX dans l''offre.
D7 - Respect de la réglementation ATEX', 'oui', 'Mettre le zonage ATEX dans l''offre peut faire peur au client', '1- Récupérer le zonage ATEX sur le WIKI et l’intégré à l’offre sous forme d’annexe', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'germain.lheriau@naskeo.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCM2 - Absence de mode opératoire de vérification des notices d''instruction', 'NASKEO', '2024', 'nc_qualite', 'CONSTRUCTION', 'QUALIMETHA', 'Il manque le mode opératoire de vérification des notices d''instruction.
D5 - Notices d’instructions des machines en respect du code du travail', 'oui', 'Dans les spécifications techniques sont rajoutées la référence à la directive machine §1.7.4.2 concernant la notice d’instruction attendue.', '1- faire le point sur la NC', '1- Rédaction du mode opératoire et diffusion au service réalisation
Vérification réalisée par IRéa lors de la constitution du DOE.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2024-07-12', 'P-Sup4', 'cloturee', 'Bug Microsoft - sauvegarde de fichiers .TMP sur le serveur', 'KEON', 'KEON', 'nc_qualite', NULL, NULL, 'Lorsqu''un fichier est ouvert par un collaborateur, Windows enregistre de façon temporaire un fichier temp sur le réseau. Ce fichier tmp disparait normalement après la fermture du fichier par le salarié. Or, depuis quelques mois, les fichiers tmp ne sont plus effacés. Bug remonté à Microsoft, irrésolu à ce jour. Pose des pbs de stockage', 'oui', 'Bug Microsoft non corrigé à ce jour', '1-Faire tourner des programmes qui vont identifier les fichiers tmp et les suppriment, pour libérer de l''espace de stockage.', 'Suivi de la résolution du bug avec Nirwana', NULL, NULL, 'patrick.foltzenlogel@keon-group.com', 'bruno.lucas@naskeo.com'),
('2024-07-12', 'P-Op5', 'cloturee', 'Problème installation titrateur HACH LANGE', 'SYCOMORE', 'OUZO', 'nc_qualite', 'LABORATOIRE', NULL, 'Livraison en direct chez le client d''un titrateur HACH LANGE. Déplacement de EHU pour installation, mise en service et formation. A la mise sous tension, écran du titrateur noir avec bandes verticales.', 'oui', 'Livraison du matériel en direct sur site. Pas de vérification demandée au client avant installation par EHU.', '1- Demande d''un retour de matériel neuf au fournisseur pour réparation ou changement. Installation et formation en visio pour éviter un nouveau déplacement de EHU.', 'Dorénavant, il sera demandé au client de mettre sous tension l''appareil dès réception pour vérifier qu''il s''allume correctement. Cela évitera un déplacement inutile d''un technicien de laboratoire.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-07-12', 'P-Op4', 'cloturee', 'NCm1  - Absence mention TQC sur PID', 'NASKEO', '2024', 'nc_qualite', 'CONSTRUCTION', 'QUALIMETHA', 'Manque mention TQC sur PID
E6 - Représentation des flux du projet', 'oui', 'nombreuse Modification du PID donc quand acter le TQC', '1- Réalisation de la procédure de fin de chantier et démarrage', 'Idem', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'nicolas.kocet@naskeo.com'),
('2024-07-12', 'P-Op5', 'cloturee', 'Non identification des échantillons de suivi biologique', 'SYCOMORE', 'LABO', 'nc_qualite', 'LABORATOIRE', NULL, 'Pendant les congés de PRA; EHU en charge des analyses à réaliser. A la réception des enveloppes de suivi biologique ouverture sans faire attention que les flacons n''étaient pas identifiés. Risque de confusion entre le digestat d''un site 1 ou 2. Afin d''avoir l''information; récupération de l''enveloppe d''origine pour retrouver l''adresse d''enlèvement.', 'oui', 'Confusion dans les prélèvements de digestats réceptionnés ;
Réception d''échantillons non identifiés;
L''exploitant ne renseigne pas systématiquement les flacons envoyés.', 'Jusqu''à aujourd''hui à chaque ouverture d''enveloppe, vérification que les flacons soient bien identifiés. Si ce n''est pas le cas le technicien les identifie au marqueur indélébile en indiquant le nom du site, la date et le type d''échantillon (Digestat 1; 2 ...)', '1- modification de la procédure d''échantillonnage (doc : "Echantillonnage des digestats") en intégrant la partie identification. 
2- Document à transmettre par mail à l''exploitant à chaque envoi de kit. 
3- Rédaction d''une fiche "Consignes identification des digestats" à intégrer systématiquement dans le kit de suivi biologique envoyé en début de MES ou de contrat de suivi biologique.

Continuer à vérifier à chaque ouverture d''enveloppe que l''identification par l''exploitant a bien été faites.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-07-12', 'P-Op5', 'cloturee', 'Erreur échantillonnage', 'SYCOMORE', 'CERE', 'nc_qualite', 'LABORATOIRE', NULL, 'Analyse urgente avec un échantillon à prélever.
La nature de l''échantillon à prélever a bien été identifié entre le laboratoire et le Responsable SPV Est. L''information ne serait pas redescendue correctement à l''exploitant qui s''est trompé dans l''échantillonnage. Un des flacons n''a pas été rempli car le préleveur n''avait pas les infos.', 'oui', 'Nécessité de faire un renvoi d''échantillon
Erreur d''échantillonnage
Problème dans la transmission des informations entre le Labo, le responsable SPV Est et l''exploitant du site.', '1- un nouvel envoi de glacière avec flaconnage a été programmé pour faire partir un nouvel échantillon.
Obtention du rapport d''analyses retardé de quelques jours.', '1- Faire un CR des infos communiquées entre le laboratoire et la personne en charge du site en mettant bien en copie la personne qui prélève l''échantillon.

En cas de doute du préleveur, ne pas hésiter à appeler le laboratoire pour plus de précisions. Tous les flacons envoyés doivent être remplis.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-07-12', 'P-Op5', 'cloturee', 'Appareil BMP', 'SYCOMORE', 'INDU', 'nc_qualite', 'LABORATOIRE', 'Labo M', 'Deux lignes sur 15 de notre appareil de mesure de BMP (AMPTS II) sont bouchées. Pour pouvoir procéder à la maintenance de ces deux lignes, nous devons arrêter tout le système de mesure qui tourne en continu.
Nous allons donc être obligées d''attendre que toutes les analyses en cours s''arrêtent pour pouvoir tout stopper et faire la maintenance de tout le système. Aucune autre analyse ne va pouvoir être effectuée le temps que celles en cours s''achèvent et le temps d''effectuer les travaux de réparation, ce qui représente au moins 4 semaines d''interruption.
Une série de 5 échantillons va donc être retardée à moins de passer sur un autre système de mesure si ce dernier est disponible en sachant qu''il appartient à METHYS et qu''il est pratiquement à 100% de sa charge.', 'oui', 'Appareil en fonctionnement 24h/24 où les maintenances sont difficilement réalisables puisqu''il doit être complètement à l''arrêt pour être nettoyé et entretenu.', '1- Utilisation du passeur de METHYS (INRAE transfert) pour lancer les prochaines analyses afin de vider l''AMPTS et faire la maintenance.', '1- Etude de l''achat d''un nouvel AMPTS pour avoir plus de disponibilités et plus de souplesse au niveau des opérations de maintenance.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-06-03', 'P-Op5', 'cloturee', 'sonde du titrateur defectueuse SODIPRO', 'SYCOMORE', 'INDU', 'nc_qualite', 'LABORATOIRE: P-Op5', 'SODIPRO', 'Remplacement de la sonde du titrateur HACH LANGE début décembre par une sonde neuve en stock au laboratoire. Nouvelle sonde non détectée. Contact du fournisseur SODIPRO et renvoi de la sonde neuve le 07/12/2023. 
Réception de la sonde de remplacement soit disant neuve début février. Au déballage, il a été constaté qu''elle était sale et usagée. D''autre part, elle ne fonctionnait pas non plus. Renvoi de nouveau de cette sonde pour en recevoir une neuve qui fonctionne le 14/03/2024. Plus de 3 mois d''attente pour ce remplacement. Nous avons pu continuer nos analyses en empruntant chaque semaine la sonde disponible sur le titrateur de l''INRAE.', 'oui', 'Sonde pH, pièce d''usure qui doit être remplacée annuellement. Commande faites chez SODIPRO (intermédiaire de HACH LANGE) car tarif plus intéressant.', '1- Emprunt de la sonde pH de l''INRAE une journée par semaine pour palier à toutes les analyses de suivi biologique. 
', '1- Commande en direct chez HACH LANGE même si le coût est un peu plus élevé chaque année.

Lorsque la sonde commence à être difficilement étalonnable annonçant des signes de faiblesse, commande d''une nouvelle sonde chez HACH LANGE. Vérifier que la sonde est en bon état de marche dès sa réception.', NULL, NULL, 'emilie.huline@sycomore-services.com', NULL),
('2024-03-01', 'P-Op5', 'cloturee', 'reception fournisseur', 'SYCOMORE', 'SURG', 'nc_qualite', 'PIECES', 'SUMA', 'la pièce livrée n''est pas la bonne', 'non', 'produit mal étiqueté
mauvaise vérification à réception
re étiquetage interne non réalisé', '1- Re étiquetage du produit ', '1- Ré étiquetage interne du produit (courant été)', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2024-11-13', 'P-Op5', 'cloturee', 'Surfacturation du client', 'SYCOMORE', 'SEGA', 'nc_qualite', 'LABORATOIRE', 'Silliker MERIEUX Nutriscience', 'Surfacturation du fournisseur pour des analyses de salmonelles non conformes du fait d''une contre analyse de vérification sous la norme NF-EN-ISO 6579-1 + ajout d''une ligne de préparation échantillons qui n''existaient pas avant le 01/01/23. Prestations vendues à perte sur le 1er trimestre 2023.', 'oui', 'Travail avec ce sous-traitant depuis 3 ans ; pas de contre-analyses jusqu''au 01/01/2023 en cas de suspicion de salmonelles ni de lignes de préparation.', '1- Appel des clients  pour les prévenir de cette surfacturation. 
2- Une partie a été prise en charge par SYCOMORE afin que le client ne soit pas 100% impacté par ces hausses.', '1- Intégrer les lignes de gestion des analyses non conforme à nos devis. 
2- Ajout d''une mention particulière à la ligne salmonelles : "Si suspicion de salmonelles, analyse complémentaire suivant la méthode NF EN ISO 6579-1 entraînant un surcoût de 116,18€ par échantillon suspect"', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-11-06', 'P-Op5', 'cloturee', 'Suivi biologique', 'SYCOMORE', 'BION', 'nc_qualite', 'LABORATOIRE', NULL, 'Délai de rendu des résultats AGV trop longs : plus de 8 jours ouvrés.', 'oui', 'Prestation qui combine de la sous-traitance et de l''analyse en interne (AGV). Attente des résultats de la sous-traitance pour envoyer l''ensemble des résultats.', '1- Envoi des résultats partiels AGV sous 2 à 3 jours ouvrés et le rapport complet une fois que la sous-traitance a transmis ses résultats.', '1- A chaque prestation double (interne et externe), transmettre des rapports partiels.', NULL, NULL, 'emilie.huline@sycomore-services.com', NULL),
('2024-01-25', 'P-Op5', 'cloturee', 'Suivi biologique en cours', 'SYCOMORE', 'BOUR', 'nc_qualite', 'LABORATOIRE', NULL, 'Interruption du suivi biologique du client car ligne masquée par inadvertance dans le planning de programmation des envois.', 'oui', 'Masquage des lignes lorsque le contrat est terminé. Ligne toujours active masquée par inadvertance d''où l''arrêt du suivi biologique.', 'Contact du client et reprise du suivi biologique là où il avait été interrompu. Prolongement du contrat du nombre d''envois ratés.', 'Etre vigilent au moment du masquage des lignes pour éviter que l''erreur se reproduise.', NULL, NULL, 'emilie.huline@sycomore-services.com', NULL),
('2024-03-04', 'P-Sup4', 'cloturee', 'Non respect nomenclature', 'KEON', 'KEON', 'nc_qualite', NULL, NULL, 'La nomenclature pour nommer les fichiers est difficile à comprendre au niveau du code affaire devons nous mettre l’activité également? 
On ne parle pas des autres sociétés que Naskeo 
Le logo n’est pas le bon', NULL, 'La nomenclature n’est pas identique à chaque société et chaque société', 'Relance auprès de Hans', 'Convocation de Hans au comité de direction afin de modifier cette nomenclature', NULL, NULL, NULL, NULL),
('2023-12-07', 'P-Sup4', 'cloturee', 'Lenteur Divalto', 'KEON', 'SKEON', 'points_vigilance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'patrick.foltzenlogel@keon-group.com', NULL),
('2023-10-16', 'P-Op4', 'cloturee', 'Surcout maintenance Déconditionneur', 'SYCOMORE', 'GATD', 'points_vigilance', 'MAINTENANCE', NULL, 'Surcout des couts de maintenance prévisionnelles du déconditionneur considérés pour l''élaboration du BP initial.', NULL, 'Couts de maintenance du fournisseur du déconditionneur green creative estimé par NASKEO pour construction du BP erronés : une partie des couts n’ont pas pris en compte. Suite demande d’explication de JYG, le service commercial a indiqué que la demande n’était pas complète, alors que la demande est de prévoir les couts de maintenance des équipements que NASKEO proposent dans leur CEM.', 'Pas d''action proposée', NULL, NULL, NULL, 'marie.david@ter-green.com', NULL),
('2023-04-03', 'P-Op4', 'cloturee', 'Coût raccordement utilités', 'NASKEO', 'GATD', 'points_vigilance', 'BUREAU D''ETUDES MOE/ETD', NULL, 'Surcout important sur le poste "raccordement utilités" pour la maitrise d''ouvrage et perte des subventions que nous aurions pu avoir sur ce poste, qui est éligible aux subventions.', 'oui', 'Budget réseau tranchées mal estimé en phase de conception par la MOE, qui a considéré la limite parcellaire du site et non le point de raccordement du fournisseur (gaz, eau, élec, ect) : 50ml estimé car la MOE pensait que les services publiques allaient fournir les utilités en limite de propriété', '1- indiquer dans le CDC TG la limite de prestation et le raccordement aux utilités, qui ne s’arrête pas à la limite de site mais au réseau

2- Coté BE, mettre en place un master raccordement utilité ?

3- Personnes au courant de ce dossier et qui pourraient compléter ces propositions : JYG / MMA / MGR / MPA', NULL, NULL, NULL, 'marie.david@ter-green.com', NULL),
('2023-06-12', 'P-Sup1', 'cloturee', 'PV - Plan de contrôle', 'KEON', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'Le pilotage des processus n’est pas assuré de façon homogène. Pour certains les objectifs ne sont pas ou peu définis et suivis, il n’est pas remonté de NC/réclamations clients identifiées ni d’actions d’améliorations (ex ; P1 – P2 – P3 – P5). La boucle d’amélioration continue demande à être plus formellement démontrée pas ces processus concernés.', NULL, NULL, '1- Faire un mail à tous les pilotes pour leur rappeler l''objectif du plan de controle', NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2023-10-18', 'P-Sup1', 'cloturee', 'PV - Analyse des indicateurs', 'KEON', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'Pour plusieurs processus les objectifs qualité témoignant de leur efficacité pourraient être redéfinis et suivis. Lorsqu’ils ne sont pas atteints, une analyse devrait conduire à des actions d’amélioration.', NULL, NULL, '1- Mettre en place une analyse annuelle sur les indicateurs de suivi', NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2024-08-12', 'P-Op5', 'cloturee', 'Erreur de préparation de commande', 'SYCOMORE', 'CHAY', 'nc_qualite', 'PIECES', NULL, 'LE CLIENT A RECU LA MAUVAISE PIECE', 'non', 'ERREUR DE PREPA 
MANQUE DE TEMPS POUR PREPA
SOUS EFFECTIF', '1- Envoi de la bonne pièce
2- Récupération de la mauvaise pièce ', '1- Embaucher pour avoir plus de temps pour la préparation des commandes ,', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com');
