INSERT INTO public._nc_staging VALUES
('2025-11-21', 'P-Op6', 'nouvelle', 'Vigilance sur la mise à disposition dans QADRO des BSD/DAC et qu''ils soient signés et tamponnés par le site lorsque BSD demandés par le fournisseur.', 'CERES', 'CERE', 'points_vigilance', 'EXPLOITATION', 'Satisfaction client', 'Manque des BSD datés signés pour des gisements bien identifiés par TEIKEI (ROE = méthaplus et méthamix). TEIKEI va refaire une liste des documents à devoir fournir aux fournisseurs lorsqu''ils en font la demande.', 'oui', 'Oubli de le personne qui réceptionne sur le site de le prendre et/ou de le signer et/ou de la dater et/ou de le verser dans QADRO', NULL, '1/ Insister et communiquer auprès des équipes de l''importance de ces documents (vérifier mise en place procédure visible à l''accueil), 
2/ Faire une formation sur les pièces réglementaires et celles à fournir dans QADRO ?
3/ Faire signer une attestation de prise en compte ?', NULL, NULL, 'anne.rivron@teikei.fr', 'Alexandre.Piton@keon-group.com'),
('2025-12-04', 'P-Op5', 'nouvelle', 'AMELIORATION CONTINUE DIGITALE', 'SYCOMORE', 'PSTOC', 'axe_amelioration', 'PIECES', 'DIVALTO', 'une liste de d''axes d''améliorations à été transmise au SI afin de pouvoir mieux gérer et monitorer un certain nombre de paramètres dans Divalto tels que CBN, classification ABC, taux de service...', NULL, NULL, 'tickets IT en cours', 'tickets IT en cours', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-09-18', 'P-Op5', 'nouvelle', 'Usure prématurée de lobes', 'SYCOMORE', 'MOUT', 'nc_fournisseur', 'PIECES', 'vogelsang', 'Apres 30 minutes d''utilisation seulement, le client a constaté une usure des lobes anormale.', 'ne_sais_pas', 'NSPP', 'faire réclamation fournisseur, 
réclamer avoir fournisseur
faire avoir client', 'NSPP', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2026-03-06', 'P-Op4', 'nouvelle', 'Gestion du suivi des garanties', 'NASKEO', 'EINDU', 'axe_amelioration', 'CONSTRUCTION', NULL, 'La gestion du suivi des garanties lors d''une déclaration client sur un équipement défectueux est à clarifier. 
A ce jour, nous ne savons pas si le suivi est opéré par le service mise en route, le service réalisation ou bien une autre personne. 
Nous n''avons également pas d''outils simples et efficaces pour assurer le suivi et ainsi mieux communiquer avec les clients. ', NULL, NULL, NULL, 'Organiser les gestion et le suivi des garanties 
Comment et qui ? ', NULL, NULL, 'betty.walheim@naskeo.com', 'betty.walheim@naskeo.com'),
('2026-03-05', 'P-Op5', 'nouvelle', 'Dysfonctionnement sur équipement neuf', 'SYCOMORE', 'NACR', 'nc_fournisseur', 'PIECES', 'VOGELSANG', 'La garniture ressort de trop. (Vu l''écart montré par le tournevis VX186-130 2) Ainsi les lobes ne touchent pas la plaque d''usure arrière (il y a environ 2mm d''espace) (VX 186-130 1). Quand la porte de la pompe est refermée les lobes frottent sur la porte (serrée correctement). Les garnitures vont dans leur logement, jusqu''en butée, mais la partie autour de l''arbre est plus épaisse et ne nous permet pas de bien loger le lobe. Nous nous demandons si les garnitures (PBT.A021) ont été modifiées ? Nous rencontrons ce problème uniquement sur les VX 186-130 Q. La pompe neuve installée commence à boire de l''huile même si elle est équipée de lobes et de plaque d''usures usagées. Si nous l''équipons de plaque d''usure neuves et de lobes neufs alors les courroies se mettent à patiner puis elles brûlent', 'ne_sais_pas', NULL, NULL, 'identifier la ou les causes ', NULL, NULL, 'christine.havenel@sycomore-services.com', 'alexandre.baffou@naskeo.com'),
('2026-02-05', 'P-Op5', 'nouvelle', 'Membrane déchirée', 'SYCOMORE', 'CANT', 'points_vigilance', 'MAINTENANCE', NULL, 'Lors du débâchage de la cuve, les techniciens ont déchiré la membrane', 'oui', NULL, NULL, 'A COMPLETER', NULL, NULL, 'christine.havenel@sycomore-services.com', 'christine.havenel@sycomore-services.com'),
('2026-02-18', 'P-Op5', 'nouvelle', 'Erreur d''identification de l''équipement pour intervention de maintenance', 'SYCOMORE', 'GATD', 'points_vigilance', 'MAINTENANCE', NULL, 'L''intervention a été programmée sur un équipement qui n''est pas celui du client. Nous n''avons pas identifié correctement la pompe du client, un devis lui a été envoyé mais le client n''a pas signalé la non conformité de l''équipement.', 'oui', 'Erreur d lecture des équipements du client', NULL, 'Valider avec le client le modèle, la marque et le numéro de série de l''équipement', NULL, NULL, 'christine.havenel@sycomore-services.com', 'christine.havenel@sycomore-services.com'),
('2026-04-09', 'P-Op6', 'nouvelle', 'Audit interne surveillance contrôle sanitaire', 'DOLE', NULL, 'nc_qualite', 'EXPLOITATION', NULL, 'absence d''audit de contrôle interne comme décrit dans l''agrément sanitaire', NULL, NULL, NULL, '1- Réaliser une trame d''audit 
2- Déployer', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Pascal.kozerawski@keon-group.com'),
('2025-06-12', 'P-Op6', 'affectee', 'Absence du DUERP', 'CERES', 'CERES', 'points_vigilance', 'EXPLOITATION', NULL, 'pas de DUERP sur le site', 'oui', NULL, '1- Mettre en place le DUERP', '1- créer une trame de DUERP => Fait par COPIL', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Alexandre.Piton@keon-group.com'),
('2025-07-25', 'P-Sup1', 'affectee', 'Intégrer RQSE aux sujet litiges', 'KEON', 'KEON', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', NULL, 'RQSE n''a pas la vu sur les litiges en cours', NULL, NULL, NULL, 'voir comment cela pourrai etre possible sans impliqué trop de temps', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-06-16', 'P-Op2', 'affectee', 'Automatisation de la remontée des données permettant de calculer automatiquement et de façon trimestrielle la marge des contrats de dev.', 'TERGREEN', 'STREG', 'axe_amelioration', 'DEVELOPPEMENT', NULL, 'Il existe actuellement un fichier de suivi de contrat de dev par projet. Ce fichier doit être alimenté par les données de la compta, de divalto (commandes fournisseurs, clients), suivi des temps. ça suppose aujourd''hui que le contrôle de gestion récupère ces données et qu''elles soient copiées dans tous les fichiers Excel. ça ne fonctionne pas bien actuellement et les marges ne sont pas à jour.', 'oui', NULL, 'Automatiser la récupération des données', 'Automatiser la récupération des données (afficher montant à facturer + montant à payer)', NULL, NULL, 'sophie.clermont@ter-green.com', 'sophie.clermont@ter-green.com'),
('2025-06-16', 'P-Op2', 'affectee', 'Automatisation la rédaction du rapport d''activité.', 'TERGREEN', 'STERG', 'axe_amelioration', 'DEVELOPPEMENT', NULL, 'Des rapports d''activité ont été mis en place il y a environ 2 ans. Ces rapports étaient alimentés en partie par le questionnaire Divalto et en partie par des données entrées à la main directement dans les fichiers. Le problème est que le master continue à évoluer et c''est très compliqué d''intégrer ces évolutions dans tous les fichiers déployés. Par ailleurs, ces données peuvent être utiles à d''autres services de l''entreprise ainsi que pour le suivi des audits et il serait utilise qu''ils y aient facilement accès. Enfin, il s''agirait de faciliter l''ergonomie et la saisie. Les fichiers sont donc aujourd''hui pas totalement à jour et pas facilement lisibles. ', 'oui', 'Travail avec Exel', 'Revoir le support, passer par des questionnaires, teams...', 'Revoir le support, passer par des questionnaires, teams...', NULL, NULL, 'sophie.clermont@ter-green.com', 'sophie.clermont@ter-green.com'),
('2025-09-11', 'P-Sup5', 'affectee', 'Indicateur processus', 'KEON', NULL, 'axe_amelioration', 'ACHAT', NULL, 'absent d''indicateur', NULL, NULL, NULL, 'absence d''objectif chiffré', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'alexandre.baffou@naskeo.com'),
('2025-09-11', 'P-Sup1', 'affectee', 'PV4. Procédure interne', 'KEON', '2025', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'Audit interne ISO', 'présence de procédure interne mais celle-ci n''apparaissent as dans la description du processus', NULL, NULL, NULL, 'indiquer l''existence de procédure interne lorsque celles-ci existent', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-09-25', 'P-Op5', 'affectee', 'Attestation de contrôle des équipements', 'SYCOMORE', NULL, 'points_vigilance', 'LABORATOIRE', NULL, 'absence d''attestation de contrôle des équipements utilisés pour les analyses.', NULL, NULL, NULL, 'demander à l''INRAE les attestations de contrôle pour s''assurer du bon fonctionnement de l''équipement.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'emilie.huline@sycomore-services.com'),
('2025-10-02', 'P-Op5', 'affectee', 'Reprendre le processus outiller', 'SYCOMORE', '2025', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', 'Audit interne ISO', 'manque d''information dans le processus. les pièces sont elles en stocks? départ fournisseur ou stock? ...', NULL, NULL, '- contrôler le fonctionnement ou non du visu des stock à l''Edition des devis. 
- établir un plan d''action afin de corriger les manquements si il en existe.

La disponibilité des pièces est visible en faisant un clic droit sur la case quantité lors de la saisie de la ligne du devis.
Une colonne "Dispo" est proposée dans les outils Divalto mais aucun affichage (pièce jointe)', 'reprendre le processus avec plus de détail sur la phase devis et livraison', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-10-06', 'P-Op3', 'affectee', 'COREC PAZA : 
Consultation MOE VRD : Questionner quant à la possibilité d’intégrer la fourniture/pose des cana PEHD enterrées → MPA', 'NASKEO', 'PAZA', 'axe_amelioration', 'ETUDE MOE', 'COREC', 'COREC PAZA : 
Consultation MOE VRD : Questionner quant à la possibilité d’intégrer la fourniture/pose des cana PEHD enterrées → MPA', NULL, NULL, NULL, 'COREC PAZA : 
Consultation MOE VRD : Questionner quant à la possibilité d’intégrer la fourniture/pose des cana PEHD enterrées → MPA', NULL, NULL, 'germain.lheriau@naskeo.com', 'Jeremy.Renner@naskeo.com'),
('2025-10-07', 'P-Op3', 'affectee', 'délégation de validation des revues de conception', 'NASKEO', '2025', 'axe_amelioration', 'BUREAU D''ETUDES MOE/ETD', 'Audit interne ISO', 'La validation des revues de conception attribuée à Virgile COSTAL pourrait être formellement consignée ainsi que les règles de délégations en cas d’indisponibilité, ', NULL, NULL, NULL, 'décrire qui prend le relais de Virgile lors de ses absences', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'marion.pavat@naskeo.com'),
('2025-10-07', 'P-Sup1', 'affectee', 'PV5. Satisfaction client', 'KEON', '2025', 'points_vigilance', NULL, 'Audit interne ISO', 'La mesure de la satisfaction client a été réalisée seulement sur Naskeo en 2004 et il reste à mettre en place les actions en découlant.
Il reste également à mettre en place la mesure de la satisfaction sur l’ensemble du périmètre certifié
', NULL, NULL, NULL, 'mettre en place la satisfaction client', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-10-07', 'P-Sup1', 'affectee', 'PV6. Plan de controle', 'KEON', '2025', 'points_vigilance', NULL, 'Audit interne ISO', 'Compte tenu de la jeunesse de la refonte des processus l’avancement des plans de contrôles n’est pas homogène, pour certains les objectifs ne sont pas encore fixés ou leur définition mérite une réflexion plus aboutie (ex : P-Sup6, P-Op5, P-Sup3, P-Sup 5, P-Op2, P-Op4, P-Op6, P-Op4,     pour d’autres la mesure des indicateurs reste à finaliser (ex : P-Op4, P-Op6, P-Op4, P-Op5)', NULL, NULL, NULL, 'retravailler les indicateurs', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-11-21', 'P-Op6', 'affectee', 'Manque une livraison de BIOLID d''une boue d''amidon du 29/08 de 29t52', 'CERES', 'CERE', 'nc_qualite', 'EXPLOITATION', 'RED', 'Après vérification facture fournisseur (BIOLID) + documents de livraison = manque une livraison dans QADRO. Mail envoyé à API et EET. 
S''assurer que chaque camion déchargé a été pesé', 'oui', NULL, 'mail envoyé à API et EET', '1/ être présent au moment de l''arrivée des camions
2/ vérifier le soir ou lendemain le nombre de camion indiqué dans QADRO
3/ si documents type LV ou BSD sans livraison dans QADRO chercher pourquoi
4/ prendre comme base la planning TEIKEI envoyé toutes les vendredis pour vérifier cohérence.', NULL, NULL, 'anne.rivron@teikei.fr', 'Alexandre.Piton@keon-group.com'),
('2025-12-03', 'P-Op4', 'affectee', 'Plusieurs dossiers ont été conçus sans réalisation des études d''exécutions par la cellule études d''exécution dirigée par Simon Bigot. Deux dossiers connus à ce jour : UCAC et ANGE.
Cela présente un risque non négligeable sur la conception des usines qui ne répondrait pas aux standards de dimensionne', 'NASKEO', 'ANGE/UCAC', 'nc_qualite', 'EXECUTION', NULL, 'des règles de dimensionnement ne correspondant pas aux standards Naskeo peuvent être appliquées sur ces projets, créer des dysfonctionnements.', 'oui', 'Il convient de rappeler les règles de fonctionnement sur la conception des installations.', 'Une vérification des études déjà effectuées à minima sur ANGE
', 'Une communication sur les processus
Un tampon Exé Naskeo sur chaque document produit', NULL, NULL, 'francois.haumont@keon-group.com', 'romain.berehouc@keon-group.com'),
('2025-12-18', 'P-Op2', 'affectee', 'Demande de TADD fait par TGINTER au BE NASKEO le 23/06/2025 (Pièce jointe) 
Envoi de NBO par TGINTER sans avoir de TADD complet 
Signature de NBO par TGINTER sans avoir de TADD complet', 'TERGREEN', 'REIC', 'axe_amelioration', 'EXPORT', NULL, 'Demande de TADD fait par TGINTER au BE NASKEO le 23/06/2025 
Envoi de NBO par TGINTER sans avoir de TADD complet 
Signature de NBO par TGINTER sans avoir de TADD complet ', 'non_concerne', 'Pas de relance du BE NASKEO de la part de TGINTER pour obtenir un  TADD 
Hiérarchie n''a pas jugé utile de faire un TADD, au regard de l''urgence de signature de la NBO (suite à une alerte de la part JYG sur le sujet)  ', 'Obtenir la DATA pour mener à bien un TADD auprès des porteurs de projet : bien dresser le besoin de DATA avec le BE NASEK 
Mandater NASKEO pour l''obtention d''un TADD avant envoi d''une NBO ', 'Obtenir la DATA pour mener à bien un TADD auprès des porteurs de projet 
Mandater NASKEO pour l''obtention d''un TADD avant envoi d''un TADD ', NULL, NULL, 'megane.repplinger@ter-green.com', NULL),
('2026-02-13', 'P-Op5', 'affectee', 'JOINT DEFFECTUEUX', 'SYCOMORE', 'SOLY', 'nc_fournisseur', 'PIECES', 'SISTAG', 'Les joints commandés sont défectueux , une différence d''épaisseur a été constatée', 'ne_sais_pas', NULL, 'organiser le remplacement standard (réclamation fournisseur en cours)
Apparemment, le joint n''a pas été monté correctement, car la fuite se produit également lorsque la force de contact est inférieure à la pression interne.
Et selon notre service clientèle et le responsable de production, après avoir examiné les photos, il s''agit d''une comparaison avec des joints déjà utilisés (le joint est comprimé sous la charge) et non avec d''anciens jeux de joints (non utilisés).

Avant de commencer à rechercher les causes des fuites, nous vous demandons de clarifier les points suivants :
1. Indiquez sur les photos quel jeu de joints vous avez récemment reçu et lequel est l''ancien (utilisé ou non !).
2.  Vérifiez que le joint est correctement positionné (surface rayée ou irrégulière, mauvais centrage, étanchéité insuffisante sur les côtés) et  suivez la procédure correcte pour remplacer le joint 
3. La pâte de remplissage (matière de bourrage) contenue dans le joint transversal peut légèrement rétrécir. Cela peut provoquer une légère fuite dans la zone de passage de la plaque de vanne (joint transversal).  Il est donc important de procéder à un remplissage de temps en temps.', 'Vérifier que la procédure de remplacement est bien respectée et proposer le lien vers la vidéo', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2026-04-24', 'P-Op3', 'affectee', 'Absence d''un CR de Revue de conception à jour avant signature contrat (projet HAGU)', 'NASKEO', 'HAGU', 'nc_qualite', 'BUREAU D''ETUDES MOE/ETD', NULL, 'Absence de revue de conception à jour avant signature du contrat alors que celle-ci est prévue dans la check list.', NULL, 'Virgile n''a pas été prévenu de la signature du contrat CEM.', NULL, 'Réaliser la revue de conception et la ranger sur le serveur.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'virgile.costal@naskeo.com'),
('2026-04-24', 'P-Op3', 'affectee', 'Absence de CR de réunion sur certaine MOE (HAGU, SURG CO2, VALD)', 'NASKEO', 'HAGU', 'nc_qualite', 'BUREAU D''ETUDES MOE/ETD', NULL, 'Absence de CR de réunion régulier.', NULL, NULL, NULL, 'Remettre en place les CR et le suivi de leur réalisation', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Jeremy.Renner@naskeo.com'),
('2026-04-24', 'P-Sup2', 'affectee', 'Fiche de poste', 'KEON', NULL, 'axe_amelioration', 'RH', NULL, 'faire une mise à jour sur les fiche de poste pour s''assurer que chaque collaborateur est bien identifé', NULL, NULL, NULL, 'faire un gros travail de mise à jour et d''identification des poste', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'audrey.kabore@keon-group.com'),
('2024-07-12', 'P-Op5', 'en_cours', 'Anticiper les fermetures labo congés', 'SYCOMORE', 'CERE', 'nc_qualite', 'LABORATOIRE', NULL, 'Sur le site de CERES, demande d''analyses urgentes sur des eaux de puit pour prouver que la contamination des sols ne venait pas du site. Demande faite la semaine de fermeture du labo en période estivale. Nécessité d''attendre le retour de PRA 4 jours après pour faire partir une glacière avec la demande d''analyses.', 'oui', 'Demande d''analyse urgente
Période de fermeture du laboratoire
Pas de glacière ni contenants disponibles sur site
Pas de personnes formées autre que le laboratoire pour faire une demande d''analyses en sous traitance
Attente de 4 jours (retour de PRA) pour lancer la demande d''analyses.', '1- Envoi d''une glacière en urgence
2- Demande d''analyses faites par PRA à son retour de congés.', '1- Faire acheter une glacière dédiée à chaque SPV qui restera sur site.
2- Fournir les flaconnages pour toutes les demandes d''analyses possibles.
3- Former les exploitants aux échantillonnages à faire sur les analyses les plus connues. Quels flacons remplir? Quantité d''échantillons... pour au moins anticiper la partie échantillonnage. Cela permettrait de gagner 2 à 3 jours pour l''envoi de la glacière.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2024-09-23', 'P-Op4', 'en_cours', 'Gestion des eaux sales / propres', 'NASKEO', 'OUZO', 'nc_qualite', 'EXPLOITATION', NULL, 'Gestion des eaux sales problématiques : 
- dans les années avec des pluies importantes, les quantités de digestats liquides sont beaucoup plus importantes, dépassent les capacités de stockages des sites, qui par ailleurs ne peuvent pas épandre car les champs ne sont pas praticables
- bassin eaux sales reste plein', 'oui', '- zone définies en eaux sales importantes
- Gestion du système permettant d''orienter les eaux de pluies venant des zones ''sales" vers le bassin orage à améliorer. 
- Incorporation des eaux dans la métha limitée', '- OUZO : Reprise du système permettant d''orienter les eaux de pluies venant des zones ''sales" vers le bassin orage -> PDG
- OUZO : By pass pour envoyer de facon exceptionnelles les eaux sales vers le stockage de digestat liquide
- MAEN : reprise de certaines zones "sales" en zone "propres"', '- Attention en conception pour limiter au max les zones "sales"
- Amélioration du syst bassin orage
- attention en conception sur les quantités d''eau incorporable en métha et les quantités d''eau attendues', NULL, NULL, 'marie.david@ter-green.com', 'betty.walheim@naskeo.com'),
('2024-09-25', 'P-Op2', 'en_cours', 'Dépassement BFR', 'LES 3 DOMES', 'OUZO', 'nc_qualite', 'DEVELOPPEMENT', NULL, 'Besoin de Fond de Roulement (BFR) de 320 k€ dépassé ce qui va créer un trou de trésorerie pour les 3 Domes. 

Sujet identifié dès fin 2023. 

Le trou de trésorerie est apparu plus tard que prévu car nous n''avons pas du justifier à notre banque l''utilisation des CCA avant de tirer le prêt bancaire. Nous avons donc pu tirer 100% du prêt auprès de la banque et garder des CCA nous permettant de financer les dépassements de BFR et les COGS. 

Le trou de trésorerie va apparaitre prochainement : 
A fin Oct nous aurons 275 k€ sur le compte les 3 Domes alors que nous aurons 700 k€ à payer dans les prochains mois, soit un trou de 435 k€.', 'oui', '- BFR sous dimensionné en année 1
- Achat de stock de gisement important
- Dans le BP, certains postes sont identifiés en CAPEX mais ne sont pas immobilisé par la compta, ce qui vient également creuser le BFR.', '

1- Prévoir une réunion pour aborder: 
-MDA : Dépôt NC + Plan de trésorerie des CAPEX restants projet de métha + les nouveaux CAPEX pour les  PV et CO2 , les apports CCA PV/CO2  et le pret PV/CO2 
-JYG : préparation budget tréso gisement
-CMA :  Projection du plan de tréso pour reconstitution du fond de roulement et remboursement des CCA qui ont été utilisé pour l’achat de matière ? 

Création d''un compte bancaire séparée pour la gestion des CAPEX PV/CO2.', '- Cadrer avec Corinne les éléments qui peuvent etre immobiliser ou ceux qui doivent rentrer dans le BFR ou dans l''exploit année 1. Réunion fixée le 06/11/2024 (salaires avant MES?, Frais comptables (prestation KEON)?, Frais de formation ?, Contrôles réglementaires année 1 ? Elec / eau avant mise en service ? Ensemencement donc transport ? )
- Cadrer le besoin de stock de gisement nécessaire pour les projets avec JYG. 
- Liste des éléments constituant le BFR a ajouter dans le master BP par ACH
- Possibilité d''avoir un BFR plus important en année 1, car ces frais ne se répliqueront pas les années suivantes. Autre moyen de les financer ? ACH / SCL
- Pour avoir une meilleur visibilité des dépenses CAPEX et des dépenses liées à l''exploitation, créer 2 comptes bancaires différents

- Sur DIVALTO, une commande peut etre en immo alors que les lignes la composant ne sont pas immobilisées : bloquer le fait que la commande et les lignes peuvent etre imputées différemment ? -> HMO', NULL, NULL, 'marie.david@ter-green.com', 'sophie.clermont@ter-green.com'),
('2024-09-02', 'P-Op2', 'en_cours', 'Livraison de matière avant la fin des travaux des plateforme de stockage', 'TERGREEN', 'MAEN', 'points_vigilance', 'EXPLOITATION', 'Agriculteurs partenaires', 'Livraison des CIVEs sur site avant que les silos ne soient étanchés. Un première livraison de CIVEs a été effectuée et les jus n''ont pas pu être récupérés.', 'oui', '- Non anticipation de la date de livraison des CIVEs entre les agriculteurs et la MOE/CEM pour essayer d''adapter le phasage du chantier en fonction des besoins client
- Retard du chantier', '1- Réalisation d''une adaptation temporaire entre les Silos et les réseaux d''évacuation des eaux sales pour permettre la récupération des jus des livraisons de CIVEs suivantes.', '1- Anticipation des périodes de livraison de matière demandées par les apporteurs de matières dès le début du projet pour adapter le planning de réalisation des travaux si possible, ou trouver une autre solution de stockage temporaire le temps que les gisements puissent être acceptés par le site.', NULL, NULL, 'marie.david@ter-green.com', NULL),
('2024-10-28', 'P-Op4', 'en_cours', 'Absence AF', 'NASKEO', 'SNASK', 'points_vigilance', 'EXECUTION', NULL, 'Depuis plus de 6 mois, les metteurs en route travaillent sans AF. Risques identifiés :
-Chaînes de sécurité réalisée uniquement sur les REX et non pensé en amont
-Des principes de pilotage d’équipements de même catégorie différents entre site sans raison particulière. Exemple ergénium continu (LAPE)
-Des mises en service de nouveaux équipements sans AF
•	Trémie LEGRAS PROM 
•	Couple trémie Pumpe + PMX (CAZI ) : je pense sincèrement qu’une réelle réflexion en phase conception sur les règles de pilotage aurait permis d’éviter ce type de soucis (débordement trémie)
-"Bidouillage" car principe de fonctionnement non réfléchi en amont, manque logique sur la conception mécanique et élec par la suite', 'oui', 'Plus d''AF rédigée par le BE', 'Réintégration des AF dans le scope BE avec mise en place d''une revue en phase conception en impliquant la mise en service et la réalisation', 'Réintégration des AF dans le scope BE avec mise en place d''une revue en phase conception en impliquant la mise en service et la réalisation', NULL, NULL, NULL, 'bruno.lucas@naskeo.com'),
('2025-03-25', 'P-Op2', 'en_cours', 'Défaillance du circuit d''approbation interne de la TS bancaire et de la convention d''actionnaire', 'TERGREEN', 'ANGE', 'nc_qualite', 'EXPORT', NULL, 'Processus de validation complexe faisant intervenir plusieurs organisations internes (développeurs Keridis, CA Keridis, CODIR KEON, CS KEON) et externes (co actionnaires, partenaires)
Timing de validation contraint par le planning de développement du projet', 'oui', 'Processus de validation des projets développés par Keridis inexistant', '1- Construire un processus de validation avec Keridis.
2- Construire un logigramme du cadre décisionnel des différentes parties impliquées dans le processus de validation', '1- Anticiper au maximum les validations requises
2- Repartir les prises de décisions / approbation entre les différentes organisations en fonction des pouvoirs de chacune  
3- Communiquer le processus à l''ensemble des parties', NULL, NULL, 'gregoire.bour@keon-group.com', 'gregoire.bour@keon-group.com'),
('2025-03-27', 'P-Op3', 'en_cours', 'Pb d''organisation pour la préparation de la visite Agrément sanitaire', 'KEON', 'GATD - AKENE 45', 'points_vigilance', 'DEVELOPPEMENT', NULL, 'AKENE 45 : Agrément sanitaire - La préparation à la visite de la DDSPP - les parties n''avaient pas été rassemblées pour la préparation et pas de procédure claire sur le déroulement de cette préparation afin d''être le plus rigoureux possible pour les obtentions rapides des agréments sanitaires.', 'oui', 'Pas de procédure écrite ', 'Définir par les équipes DEV/REG/TEIKEI/EXPLOIT une procédure pour préparer les visites réglementaires (Agrément) ', NULL, NULL, NULL, 'gwenaelle.jacq@teikei.fr', 'florence.martin-sisteron@naskeo.com'),
('2025-04-04', 'P-Sup2', 'en_cours', 'Absence de suivi de formation obligatoire', 'KEON', 'SKEON', 'points_vigilance', 'RH', NULL, 'Formation nécessaire (obligatoire) aux équipes (exploitation, maintenance, SPV...) non faites ou recycler (CACES, habilitation elec ...)', 'oui', 'Absence de suivi de formation obligatoire.
Changement du SIRH, pb d''accès au droit par les managers', 'Prise en main par R Rh pour faire les demandes à la place des managers.

 ', 'Recruter un directeur industriel pour suivre le coté sécurité.
Check list des infos a suivre par les managers.
Suivre les formations et leurs durées de validités.', NULL, NULL, 'amaury.foulonneau@keon-group.com', 'camille.bolo@keon-group.com'),
('2025-06-12', 'P-Op6', 'en_cours', 'Plan de site absent à l''entrée', 'CERES', 'CERES ', 'points_vigilance', 'EXPLOITATION', NULL, 'le plan de circulation n''est pas à jour sur le site', 'oui', 'Le temps n''a pas été pris pour la  mise à jour du plan de circulation', '1- Commander le panneau au service communication marketing', '1- créer les consignes à mettre sur le plan de circulation => Fait par FMS', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Alexandre.Piton@keon-group.com'),
('2025-07-04', 'P-Op6', 'en_cours', 'Présence d''indésirables dans les matières stercoraires : 01/07/2025, casse de 5 boulons de sécurité sur Prémix de Dole', 'TEIKEI', NULL, 'nc_fournisseur', 'ACHAT', NULL, 'Présence d''indésirables dans les matières stercoraires : 01/07/2025, casse de 5 boulons de sécurité sur Prémix de Dole', NULL, NULL, 'Exceptionnel : incident remonté au fournisseur pour faire une remontée au producteur.', NULL, NULL, NULL, 'Alexandre.Piton@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-07-17', 'P-Op6', 'en_cours', 'Non respect planning appro Semaines 28 et 29', 'TEIKEI', 'CERE', 'nc_fournisseur', 'ACHAT', NULL, 'NOn respect planning :
Manque des apports de Pulpe de Tomate (S28 3 pour 6 au planning S29 0 à Jeudi 17/07 pour 4) => augmentation des MS
Décalage Graisse S28 a conduit a alimenter de force le méthaniseur => dépassement FOS/TAC 
Décalage CHR => augmetation MS', NULL, NULL, 'Rappel des règles aux transporteurs', NULL, NULL, NULL, 'Alexandre.Piton@keon-group.com', 'florian.neute@teikei.fr'),
('2025-07-25', 'P-Sup1', 'en_cours', 'revoir la méthode de satisfaction client', 'KEON', 'KEON', 'nc_qualite', 'QUALITE - ISO - QUALIMETHA', NULL, 'assurer un continuité sur cette démarche', NULL, NULL, NULL, 'acter une procédure interne précise', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-07-25', 'P-Op2', 'en_cours', 'Levée des réserves', 'TERGREEN', NULL, 'axe_amelioration', 'DEVELOPPEMENT', NULL, 'En fin de projet après construire TerGreen suit la levée des réserves', NULL, NULL, NULL, 'formaliser ce suivi coté TG', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'sophie.clermont@ter-green.com'),
('2025-07-25', 'P-Op5', 'en_cours', 'Gestion des stocks - Tx de service', 'SYCOMORE', 'PSTOC', 'axe_amelioration', 'PIECES', NULL, 'limiter les erreurs de livraison et maitriser les stocks', NULL, 'Optimiser: Tx de service, tx de renouvellement, ....', 'être en capacité de maitriser le calcul et le monitoring du taux de service', '-Améliorer la gestion des Stocks', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'nicolas.narolles@sycomore-services.com'),
('2025-08-19', 'P-Op2', 'en_cours', 'Satisfaction client Ter Green', 'TERGREEN', 'KEON', 'axe_amelioration', 'DEVELOPPEMENT', NULL, 'absence d''évaluation satisfaction client', 'non_concerne', NULL, NULL, 'Mettre en place la satisfaction client en 2026', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'francois.haumont@keon-group.com'),
('2025-08-19', 'P-Op5', 'en_cours', 'Satisfaction client Teikei', 'TEIKEI', 'KEON', 'axe_amelioration', 'APPROVISIONNEMENT', NULL, 'Absence de satisfaction client', NULL, NULL, '1 - Réaliser la liste des clients => Site méthanisation 
2 - Ecrire la procédure de réalisation d''enquête satisfaction client.
3 - On déterminer ceux que l''on souhaite enquéter', 'Mettre en place une satisfaction client en 2026', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'francois.haumont@keon-group.com'),
('2025-08-29', 'P-Op3', 'en_cours', 'Absence de plan DWG à jour sur le serveur', 'NASKEO', 'FOUC', 'nc_qualite', 'BUREAU D''ETUDES MOE/ETD', NULL, 'GMO est parti en congés sans avoir remis certains plans DWG à jour sur le serveur après une journée de télétravail.', 'oui', 'travail en local probablement pour cause de lenteur sur le VPN', NULL, 'Avoir une routine pour remettre en fin de journée les plans DWG à jour sur le serveur. ', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'marion.pavat@naskeo.com'),
('2025-09-05', 'P-Op6', 'en_cours', 'Défaut communication sur EPI', 'KEON', 'SKEON', 'points_vigilance', 'EXPLOITATION', NULL, 'Définition du matériel EPI nécessaire aux visites sur site validé en COPIL SST notifiant la volonté de ne pas utiliser de système amovible coquet pour la protection des pieds. L''exploitation n''a pas reçu l''information et commande ce matériel pour équiper les sites voir les collaborateurs KEON', 'oui', '- non cascade des directives validées en COPIL SST sur les équipes ', '1. FMS contacte ETA pour faire un point de validation', '1. Inviter ETA au copil SST
2. Recap du CR mettant en avant "les grandes décisions" à envoyer au CODIR avec CR complet', NULL, NULL, 'claire.sassias@keon-group.com', 'florence.martin-sisteron@naskeo.com'),
('2025-09-05', 'P-Sup3', 'en_cours', 'Validation des différentes étapes d''un projet com', 'KEON', 'CKEON', 'axe_amelioration', 'COMMUNICATION - MARKETING', NULL, 'En dehors des emails échangés avec les équipes internes ou externes, nous n''avons pas de jalons visibles de validations des différentes étapes de production (conception, création, production...)', NULL, 'pas d''outils adapté à ses validations', 'Veiller à avoir un mail de validation à chacune de ces étapes. Bien sensibiliser les équipes com de l''importance d''un jalon visible de validation à chaque étape.', 'Mettre en place des checks de validations dans le nouvelle outils de suivi des projets de la com + former les équipes à l''importance de ces jalons.', NULL, NULL, 'claire.sassias@keon-group.com', 'claire.sassias@keon-group.com'),
('2025-08-28', 'P-Sup6', 'en_cours', 'Installation de matériel technique sur site R&D (débimètre, ...)', 'NASKEO', 'RGENE', 'axe_amelioration', 'R&D', NULL, 'Difficultés rencontrées lors de l''installation du matériel débimètre par l''équipe R&D, accompagnée par les filiales du groupe KEON (Sycomore, Naskeo).

A deux reprises, malgré des échanges avec les services référents, échec d''installation du matériel débimètre sur site, alors qu''il est au coeur des expériences R&D', 'oui', 'Les raisons : 
> Difficultés de communication et compréhension entre services aux compétences différentes
> Absence d''AMO compétent en interne / avec la bande passante suffisante pour suivre le sujet 
> Installation trop petite et spécialisée pour être réalisée en service CEM par les filiales KEON dans son ensemble
', 'Une sous-traitance externe (AMO ou installation CEM) sera désormais réalisée', 'Une sous-traitance externe (AMO ou installation CEM) sera désormais réalisée

Vigilance sur les installations de l''ensemble des matériels techniques sur site, en privilégiant la sous-traitance', NULL, NULL, 'manon.mangin@keon-group.com', 'Muriel.chaghouri@naskeo.com'),
('2025-09-11', 'P-Sup6', 'en_cours', 'Passation étude', 'KEON', '2025', 'axe_amelioration', 'R&D', 'Audit interne ISO', 'La passation du new business au processus concerné demande à être formellement démontrée par un enregistrement', NULL, NULL, NULL, 'A Clarifier via un document officiel. passation de responsabilité', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'manon.mangin@keon-group.com'),
('2025-09-11', 'P-Sup1', 'en_cours', 'Formaliser l''enregistrement des revues de processus', 'KEON', '2025', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', 'Audit interne ISO', 'Absence d''enregistrement et de traçabilité des revues de processus', NULL, NULL, NULL, 'Mettre en place un suivi.
=> intégration d''une ligne de revue de processus dans le plan de contrôle ( ajout e date)', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-09-11', 'P-Sup6', 'en_cours', 'PV1. Arbitrage CODIR non accessible sur le serveur', 'KEON', '2025', 'points_vigilance', 'R&D', 'Audit interne ISO', 'La validation formelle des arbitrages par le CODIR demande à être enregistrée', NULL, 'L''arbitrage des projets est enregistré sur le serveur mais dans un dossier accessible uniquement au CODIR. ', NULL, 'Demander au CODIR d''envoyer un mail à MMA pour avoir la vue sur les arbitrage des projets', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'manon.mangin@keon-group.com');
