INSERT INTO public._nc_staging VALUES
('2024-09-06', 'P-Op5', 'cloturee', 'ERREUR LIVRAISON', 'SYCOMORE', 'PINDU', 'nc_qualite', 'PIECES', 'BORGER', 'le client a reçu une pièce à la place d''une autre', 'oui', 'non étiquetage de la référence à réception magasin
nouveau collaborateur
méconnaissance de la pièce
absence du formateur
mélange des pièces', '1- Livrer la bonne pièce 
2- Récupérer et /ou vendre l''autre.', '1- Ranger, fiabiliser, étiqueter l''ensemble du stock.
2- Transcrire les références fournisseur/interne à réception', NULL, NULL, 'nicolas.narolles@sycomore-services.com', NULL),
('2024-03-19', 'P-Op5', 'cloturee', 'Erreur de prépa liée à une erreur de stockage', 'SYCOMORE', 'pstoc', 'nc_qualite', 'PIECES', 'VOGELSANG', 'des grilles non commandées ont étés livrées à la place d''autres grilles', 'oui', 'erreur de préparation de commande du fournisseur', '1- Contrôle qualité dès réception
2- Réclamation instantanée : 23/02/24
suivi (réception des bonne le 06/03, expe des mauvaises le 06/03)', '1- communication auprès du fournisseur si répétition du problème', NULL, NULL, 'nicolas.narolles@sycomore-services.com', NULL),
('2024-03-14', 'P-Op5', 'cloturee', 'Préparation intervention maintenance outillage', 'SYCOMORE', 'MELL', 'nc_qualite', 'MAINTENANCE', NULL, 'Passerelle manquante avant intervention sur agitateur Optimix', 'oui', 'manque de communication entre coordinateur maintenance et les techniciens + manque de préparation de l''intervention (vérification du protocole d''intervention)', '1- Validation procédure 2 semaines avant intervention minimum', '1. retour d''un outil passerelle
2. + diffuser et former aux 2 protocoles d''interventio (avec et sans passerelles)', NULL, NULL, 'ronan.durand@sycomore-services.com', 'valentin.bertrand@sycomore-services.com'),
('2024-06-24', 'P-Op5', 'cloturee', 'Pas de réponse suite appel numéro d''astreinte', 'SYCOMORE', 'CAZI', 'nc_qualite', 'ASTREINTE', NULL, 'Pas de réponse suite appel du client Lionel Fouché (contrat AST)
Personnel d''astreinte en congés et pas de solution de repli', 'oui', 'Pas de continuité de service', '1- Revue hebdo du planning d''astreinte + garantie de continuité de service', 'Idem', NULL, NULL, 'francois.haumont@keon-group.com', NULL),
('2023-03-02', 'P-Op1', 'cloturee', 'Impossibilité de finaliser le BP', 'NASKEO', 'VIHI', 'nc_qualite', 'COMMERCE', NULL, 'Audit pas assez poussé pour finaliser une offre', 'oui', 'audit +++ pour finaliser le BP avant passage Codir Costrat', NULL, NULL, NULL, NULL, 'stephane.gillet@ter-green.com', NULL),
('2023-06-02', 'P-Op1', 'cloturee', 'Désengagement après remise d''une BO', 'NASKEO', 'CHAM', 'nc_qualite', 'COMMERCE', NULL, 'Changement des hypothèses BP sans fin et après la revue des audits de février', 'oui', 'le rendu des audits n''est pas suffisant pour rendre une BO. Nous devons avoir un BP finalisé en réunion bilan des audits puis Codir puis Costrat', '1- Réunion orga brownfield 4/10/2024', NULL, NULL, NULL, 'stephane.gillet@ter-green.com', NULL),
('2024-11-13', 'P-Op5', 'cloturee', 'Inversion produit', 'SYCOMORE', 'pstoc', 'nc_qualite', 'PIECES', 'SUMA', 'des agitateurs ont étés commandés avec les mauvaises helices', 'non', '-commande fournisseur non conforme
-ARC non conforme
-pas de contestation
- collaborateur proche (binôme) pas mis dans la boucle', '1- Mettre systématiquement le binôme dans la boucle
2- Relire la commande avant envoi
bien comparer l''ARC avant confirmation', 'Idem', NULL, NULL, 'nicolas.narolles@sycomore-services.com', NULL),
('2024-10-29', 'P-Op4', 'cloturee', 'ABSENCE PLAN RECOLEMENT GC suite à modifications majeures', 'NASKEO', 'ABEV', 'nc_qualite', 'CONSTRUCTION', 'NASKEO GC / CMP', 'Le fournisseur de membrane s''aperçoit qu''il est difficile de mettre la membrane sur 1 petit ouvrage. L''opération n''a pas posé de problème pour les 4 autres ouvrages dont 1 ouvrage étant quasi identique à celui incriminé. Défaut sans doute de la part du FO de membrane de ne pas avoir pris de côte sachant que les membranes sont du "sur-mesure". Le souci est surtout qu''une membrane trop courte peut se dégrader plus vite. Surcoût OPEX', 'oui', '- Absence de récolement côté fin de construction d''ouvrage côté GC;
  - Absence de prise de côtes avant élaboration de toute membrane sur mesure par le fabricant. 
 - Irea tend à ne pas faire passer le FO de membrane et transmet des côtes émanant du BET Structure qui fixent les bases théorique des cuves.', '1- mail Cellule GC à Irea ABEVE de mener l''enquete sur les sites où des problèmes similaires ont été suspecté. 

Proposition que l''Irea fasse un mail à Baur sur l''avertissement que nous allons les contrôler dorénavant.', '1- La cellule GC se note de rajouter dans les nouveaux dossier "Plans et_ou Côtes de recollement des ouvrages" dans le chemin : XXX PROJET/06 EXECUTION / 03 - CONSULTATIONS ET SUIVI CONTRACTUEL / GC CUVES / 08 - DOC & DOE / Plans et_ou Côtes de recollement des ouvrages', NULL, NULL, 'ludovic.tignon@naskeo.com', 'betty.walheim@naskeo.com'),
('2024-02-21', 'P-Op5', 'cloturee', 'Erreur de prépa liée à une erreur de stockage', 'SYCOMORE', 'GEYS', 'nc_qualite', 'PIECES', 'VOGELSANG', 'suite montage pièce, le client a constaté des fuite d''huile= non conformité pièce.
de lui même il s''est rendu chez le fournisseur qui lui a expliqué que la pièce avait dix ans et avait été reconditionnée.
les pièces ont étés remplacées par le fournisseur suite au déclanchement d''une commande fournisseur en urgence.

le client va maintenant chercher à obtenir un avoir de notre part 

nous chercherons la même chose de la part du fournisseur', 'oui', '- reconditionnement de pièces non conformes.', '1- Générer commande urgence en palliatif
2- Faire réclamation NQL fournisseur
3- Faire échange NQL/ OK fin mars max
4- Chercher puis remplacer les deux autres pièces envoyées chez un autre client. fin mars max', '?', NULL, NULL, 'nicolas.narolles@sycomore-services.com', NULL),
('2024-02-23', 'P-Op5', 'cloturee', 'RECEPTION PIECES', 'SYCOMORE', 'MAIN', 'nc_qualite', 'PIECES', 'VOGELSANG', 'à réception de sa commande (livrée en directe par le fournisseur), le client a constaté qu''un référence n''était pas celle annoncée sur le BL.', 'non', 'stock Bouguenais trop faible
commande passée pour livraison directe 
fiabilité fournisseur de plus en plus faible', '1- Etablir réclamation fournisseur FAIT19/03
2- Demander livraison conforme FAIT19/03
3- Demander enlèvement nql FAIT19/03
réclamer avoir
4- Surveiller le bon déroulement des étapes précédentes mars 24', '1- Mise en place de l''évolution du volume stocké pour garantir au mieux nos livraisons auprès de nos clients. ', NULL, NULL, 'nicolas.narolles@sycomore-services.com', NULL),
('2024-09-08', 'P-Sup1', 'cloturee', 'DURP', 'KEON', 'KEON', 'nc_qualite', 'SECURITE', NULL, 'DURP pas à jour', 'oui', 'Manque d''information, de CSE pour KEON, défaillance du COPIL', '1- Retravailler le DURP', 'Aucune', NULL, NULL, 'hugues.molto@keon-group.com', NULL),
('2024-09-21', 'P-Sup2', 'cloturee', 'Exercice incendie', 'KEON', 'SKEON', 'nc_qualite', 'RH', NULL, 'Pas d''exercice d''alerte incendie Bouguenais', 'non', 'propriétaire', '1- Contacter le propriétaire du batiment', '1- Plannifier l''exercice incendie ', NULL, NULL, 'hugues.molto@keon-group.com', 'jennifer.wilks@keon-group.com'),
('2024-02-28', 'P-Op5', 'cloturee', 'Montage piece', 'SYCOMORE', 'CERA', 'nc_qualite', 'PIECES', 'vogelsang', '4 pièces DOR0019 ont été commandées et 4pièces DOR.019 ont été expédiées. ces pièces étaient stockées sous la ref : DOR0019.
les pièces ont étés récupérées, un avoir a été fait et les bonnes pièces ont étés ajoutées à une commande en cours.', 'non', 'erreur d''étiquetage des pièces (INTERNE)
références fournisseur similaires. (EXTERNE)
non transcription des pièces de la ref externe vers interne à réception.', '1- Réaliser les régularisations de stock +/- 
2- Modifier l''étiquetage en place sur cette ref  ', '1- Réorganiser le magasin (FAIT)
2- Réétiqueter 100% des références avec un étiquetage normalisé contenant les ref internes. (en attente module Divalto)
3- Réaliser un inventaire (juillet2024)
4- Mettre en place les inventaires tournants. 
fictifs dans un 1er temps (jusqu''à decembre2024) puis officiels dans un second.(à définir)', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2024-03-07', 'P-Op5', 'cloturee', 'réception pièces', 'SYCOMORE', 'DOLE', 'nc_qualite', 'PIECES', NULL, 'PALETTE LIVREE CHEZ MAUVAIS CLIENT', 'non', 'LE TRANSPORTEUR N''A PAS LIVRE LA PALETTE CHEZ LE BON CLIENT', '1- REETIQUETAGE PUIS RELIVRAISON', NULL, NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2024-03-19', 'P-Op5', 'cloturee', 'ERREUR PREPARATION CDE', 'SYCOMORE', 'DOUE', 'nc_qualite', 'PIECES', 'SYCOMORE', 'inversion produit lors de la préparation de commande', 'oui', 'rangement pas assez précis 
pas d''étiquetages interne a réception fournisseur
intégration nouveau collaborateur', 'ccs à passer pour régule de stock (s4/24)
expéditions des Pieces voulues à l''origine (S5/24)', '1- Amélioration du rangement
2- Etiquetage interne des références interne', NULL, NULL, 'kevin.bouvron@naskeo.com', NULL),
('2024-06-07', 'P-Op5', 'cloturee', 'LOGISTIQUE', 'SYCOMORE', 'MAEN', 'nc_qualite', 'PIECES', 'SYCOMORE', 'INVERSION PRODUITS (LOBES ET PLAQUES) LORS DE LA PREPARATION', 'oui', 'ERREUR DE RANGEMENT ET MAUVAIS ETIQUETAGE STOCK SUR LES LOBES
PLAQUE : ABSENCE D''ETIQUETAGE FOURNISSEUR ET PAS DE REETIQUETAGE LOGISTIQUE', '1- RENVOI DES BONNES PIECES AU CLIENT
2- REPRISE DE LA MAUVAISE PLAQUE PAR MAXIME', '1- RANGEMENT DU STOCK LOBES 
2- REETIQUETAGE INTERNE ', NULL, NULL, 'maxime.aubree@sycomore-services.com', NULL),
('2024-09-03', 'P-Op2', 'cloturee', 'Erreur BP ( prix des Cives)', 'NASKEO', 'GIRO', 'nc_qualite', 'COMMERCE', 'Les 6 FERMES', 'erreur BP (prix des cives en tonnes de MF au lieu de MF) -> lorsque la mise à jour des taux de MS a été fait, cela a réduit le cout de gisement', 'oui', 'Prix fixe en taux de matiere fraiche', '1- Mettre les prix de cive en taux de matiere sèche - ', '1- Mettre les prix de vice en matières seches dans le BP master - 
2- Mettre en place des contrôles systématiques', NULL, NULL, NULL, NULL),
('2024-02-01', 'P-Sup5', 'cloturee', 'Exploitation', 'KEON', 'MAEN', 'nc_qualite', 'EXPLOITATION', 'KEON - Gestion Administrative et Financière', 'Insatisfaction du client sur la gestion de la facturation et volonté du client d''arrêter le contrat de gestion administrative et financier avec KEON.', 'oui', '- Non compréhension du client des taches réalisées par la compta, qui trouve que les délais sont trop long et la prestation trop onéreuse. 
- Le client n''exprime pas forcément ses besoins au bon interlocuteur
- Prestation réalisée à distance et volonté du client de la réaliser en local', 'Réunion fin Décembre entre Corine le client : 
1- Bilan trimestriels en présentiels
2- proposition de gestion des paiements par le client. Offre pour la gestion comptable uniquement à faire par Corinne. 
3- Mise en place sharepoint pour donner au client l''accès aux factures traitées.', 'Idem', NULL, NULL, 'marie.david@ter-green.com', NULL),
('2024-02-01', 'P-Op4', 'cloturee', 'Réserve chantier', 'NASKEO', 'MAEN', 'nc_qualite', 'CONSTRUCTION', 'NASKEO / CEM et MOE', 'Réserves chantier (NASKEO CEM et lots sous MOE Naskeo) non levées après plus de 6 mois d''exploitation (injection en Mai 2023)', 'oui', 'Réponses de Naskeo pour la levée de réserves non satisfaisante pour le client : solutions non satisfaisantes et/ou délais de mise en œuvre non précisé. 
Enjeux entre MOE et CEM parfois opposés et le choix de la double casquette n''est pas forcément comprise par le client.', '1- Faire une liste exhaustives de toutes les réserves (CEM et lots sous MOE) à tenir par la MOE avec les solutions proposées et les délais de mise en œuvre. 
2- Réunion à lancer par le MOE avec le client si pas de solution satisfaisante à court terme.
3- Clarification avec le client en début de projet des rôles du CEM et du MOE.', NULL, NULL, NULL, 'marie.david@ter-green.com', NULL),
('2023-12-07', 'P-Sup1', 'cloturee', 'Audit interne', 'KEON', 'KEON', 'nc_qualite', 'QUALITE - ISO - QUALIMETHA', NULL, 'Le traitement des NC via zooform n’est plus effectif depuis plusieurs mois', NULL, 'aucune personne désignée pour traiter les NC', '1- Reprendre en main la gestion des NC', '1- Trouver une solution durable', NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2023-10-13', 'P-Op4', 'cloturee', 'Bassin ES vers Ergénium', 'NASKEO', 'MAEN', 'nc_qualite', 'CONSTRUCTION', 'NASKEO / VRD', 'Le bassin ES se déverse dans la cuve ergénium sans débitmètre, ce qui ne permet pas à l''exploitation de maitriser la ration et les quantités incorporées. Risque de débordement. 
De plus, en cas de remplissage >90% du bassin ES, il se déverse dans le bassin EP. L''exploitant maintient que ceci n''est pas réglementaire (mail à FMS ce jour)', 'oui', 'Non prévu au moment de la conception ?', '1- vérification réglementaire
2- mise en place d''un débitmètre ou renvoi vers la cuve à lisier', 'A discuter', NULL, NULL, 'amaury.foulonneau@keon-group.com', NULL),
('2023-06-28', 'P-Op4', 'cloturee', 'Accès agitateur', 'NASKEO', 'MAEN', 'points_vigilance', 'CONSTRUCTION', 'SUMA', 'L''accès à l''agitateur de la cuve Ergénium ne peut pas se faire en toute sécurité. En effet, pour les maitenances hebdomadaire, l''opérateur doit etre en équilibre sur le bord de la cuve et se pencher sous la bache de la cuve (risque de chute + risque d''intoxication). Cette opéation doit etre réalisée fréquemment (parfois plusieurs fois pas semaine). Problème discuté depuis le mois d''Avril 2023 en COPIL MAEN + remonté à AJO. Adaptation faite sur site en Sept 2023 pour remonter le support de l''agitateur et le tourner à 180° pour que la maintenance est lieu hors cuve, mais l''adaptation ne permet pas de tourner l''agitateur à 180° et la maintenance a toujours lieu au dessus de la cive.', 'oui', 'Pourquoi non mis en place par Naskeo initialement ? 
-> Non prise en compte des contraintes d''exploitation et de sécurité
Pourquoi ? 
-> Soit manque de REX et de projection sur l''exploitation, soit volonté de ne pas avoir des surcouts sur le projet', 'Sept 2023 : Modification du tube de l''agitateur (cf ci-dessus)', 'EN attente solution de Naskeo. Attention, risque sécurité', NULL, NULL, 'amaury.foulonneau@keon-group.com', NULL),
('2023-02-05', 'P-Op4', 'cloturee', 'Contraintes urbanisme', 'NASKEO', 'ROMA', 'points_vigilance', 'CONSTRUCTION', 'NASKEO', 'Crainte sur le respect des distance d''urbanisme lors des travaux d''implantation de la poche souple de stockage digestat', 'oui', 'Absence de validation PC/Plan execution', 'Mettre en place étape de validation avec grille de conformité ICPE/PC et comparaison aux plans d''exécution + réunion de lancement de chantier avec parties prenantes externes et internes', 'développer les grilles de validation
tester les outils
déployer la procédure', NULL, NULL, NULL, NULL),
('2023-10-08', 'P-Op4', 'cloturee', 'Avis défavorable DDT', 'NASKEO', 'CERE', 'points_vigilance', 'CONSTRUCTION', 'naskeo', 'Courrier de notification de la DDT avec avis défavorable recu après démarrage de travaux', 'oui', 'Respect du cadre réglementaire mais absence de validation des contraintes applicables avant démarrage des travaux', 'Mettre en place une grille de validation avant démarrage de travaux pour s''assurer que les plans de réalisation respectent le cadre urbanisme et le cadre ICPE et de tenir une réunion de chantier avec les parties prenantes (uinternes et externes) en amont', 'Développement des grilles de validations type
Test sur un projet
Déploiement auprès des responsables travaux et responsables MOE', NULL, NULL, NULL, NULL),
('2025-03-01', 'P-Sup1', 'cloturee', 'VALIDATION', 'KEON', 'KEON', 'nc_qualite', 'QUALITE - ISO - QUALIMETHA', 'ZOHOFORM', 'l''accès ordinateur ZOHOFORM ne fonctionne plus', 'oui', 'non paiement de la l''abonnement', 'payer la l''abonnement', 'renouveler l''abonnement quand celui-ci arrive a son terme', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'valentin.bertrand@sycomore-services.com'),
('2023-01-01', 'P-Op2', 'cloturee', 'Surcout déplacement ouvrage - servitude', 'LES 3 DOMES', 'OUZO / GATD', 'points_vigilance', 'DEVELOPPEMENT', 'COLAS', 'Surcoût de 150 000 euros de l''entreprise de terrassement COLAS pour le déplacement de la lagune du projet OUZO. Déplacement suite à la découverte de la bande de servitude à l''autoroute et permettant de gagner de l''espace pour l''implantation du projet GATD.', 'oui', '-	Non priorisation et prise de recul du sujet par les équipes OUZO / GATD par manque de ressources
-	Manque d’information sur la réglementation / plan. 
-	Décision par Ter''Green (SCL, MDA, PMA, MMA) en l''absence de l''ensemble des actionnaires (en particulier JYG)', '1- Le devis de travaux supplémentaire a été validé à COLAS et pris en charge pour le moment par OUZO. La répartition de cette prise en charge (OUZO, GATD, Ter''green, Naskeo) est en cours de discussion. Réunion prévu sur le sujet le 07/02/2023', '
1- S’assurer des moyens mis à disposition pour atteindre les objectifs des projets
2- Grille de lecture PC/ICPE/Réglementation pour élaboration des plans et retranscription physique sur les plans par Naskeo
3- Mise en place des COPILs OUZO / GATD', NULL, NULL, 'marie.david@ter-green.com', NULL),
('2024-11-13', 'P-Op4', 'cloturee', 'démanchement tuyau', 'NASKEO', 'DAMP', 'nc_qualite', 'MISE EN SERVICE', 'MTO', 'Démanchement d''un tuyau PEHD lors des tests (mise en service)', 'oui', 'Tuyauterie non soudé', 'Réparation par le tuyauteur', 'Obligé tests en pression des canalisations avant MES (déjà demandé mais non appliqué)', NULL, NULL, 'amaury.foulonneau@keon-group.com', 'valentin.bertrand@sycomore-services.com'),
('2024-06-11', 'P-Op4', 'cloturee', 'Mise en service', 'NASKEO', 'COTT', 'nc_qualite', 'MISE EN SERVICE', 'SYCOMORE', 'Dans un mail de mise en demeure le client nous a signalé plusieurs désordres liés à la mise en service, et notamment :
- Problèmes d''automatisme,
- Problèmes sur la soupape,
- Problèmes de manque de documentation.', 'oui', 'L''équipe de mise en service n''a pas suffisamment tracé par écrit le suivi de la résolution des problèmes signalés par le client.', 'Mettre en place des points de suivi interne régulier.
Répondre systématiquement aux mails du client.', 'Mettre en place des points de suivi interne régulier.
Répondre systématiquement aux mails du client.', NULL, NULL, 'valentin.bertrand@sycomore-services.com', NULL),
('2024-03-01', 'P-Op4', 'cloturee', 'Mise en service', 'NASKEO', 'CAMP', 'incident_site', 'MISE EN SERVICE', 'SYCOMORE et son sous-traitant TEDOM-SCHNELL', 'Problèmes électriques sur le moteur TEDOM-SCHNELL qui entraine des arrêts et des pertes d''exploitation côté client.
Cette situation dure depuis plusieurs semaines et est à résoudre par SYCOMORE.', 'oui', 'SYCOMORE n''a pas suffisamment cherché à trouver un prestataire alternatif pouvant prendre le relai de TEDOM-SCHNELL à ce sujet', 'Mise en demeure de TEDOM-SCHNELL d''intervenir.
Recherche d''un prestataire alternatif.
Contacts réguliers avec le client.', 'Faire des points de suivi régulier sur les affaires.
Identifier des prestataires alternatifs pouvant prendre le relai en cas de défaillance du prestataire principal.', NULL, NULL, 'valentin.bertrand@sycomore-services.com', NULL),
('2024-03-19', 'P-Op6', 'cloturee', 'Débordement cuve', 'Autres', 'MAIN', 'incident_site', 'EXPLOITATION', NULL, 'un débordement Ergenium ( 150-200 m3 ) eu lieu cette nuit sur MAIN ( voir photo ci-jointe ). Après analyse du programme automate une sécurité était manquante sur le G7 Mode Continue, le défaut de la vanne A2VGP01 n’était pas pris en compte.', 'oui', 'Absence d''analyse fonctionnelle réalisée en phase étude par NASKEO lors des travaux de modification de l''Ergenium suite aux travaux réalisés par Atlantique Industrie', 'Tests chaîne de sécurité 11/07/22 : effectué par PGU
Modification de la programmation par ADT', 'Généralisation des AF + Tests chaîne de sécurité en phase construction et à chaque modification de process', NULL, NULL, 'valentin.bertrand@sycomore-services.com', NULL),
('2024-11-13', 'P-Op5', 'cloturee', 'ASTREINTE', 'SYCOMORE', 'OSURG', 'nc_qualite', NULL, NULL, 'Automaticien d''astreinte injoignable malgré une dizaine d''appels par l''astreinte de rang 1.', 'oui', 'Manque de rigueur de la part de la personne d''astreinte qui n''a pas en permanence son téléphone sur lui pendant son astreinte.', 'Rappeler les règles aux personnes d''astreinte', 'Organisation d''une réunion avec le responsable du service auto, de son n+2, du responsable des opérations et du commercial SYCOMORE pour remettre à plat le processus. Réunion déjà planifiée suite dernière NC sur le sujet', NULL, NULL, 'valentin.bertrand@sycomore-services.com', NULL),
('2024-03-01', 'P-Op4', 'cloturee', 'Garantie', 'NASKEO', 'CAZI', 'incident_site', 'CONSTRUCTION', 'NASKEO', 'Débordement sur site, via le Premix.', 'oui', 'La recirculation vers le Premix ne s''est pas arrêtée, la trémie a été remplie de liquide et plus de 40 m3 (propos du client) se sont déversés dans la rétention  qui est également une zone à forte circulation.', 'Intervention des automaticiens pour recontrôler le code et faire des tests : 9&10/05 (AYA et ADV).', 'L''ajout d''un capteur de présence de liquide dans la cheminée du Premix sur les sites existants en protection de débordements.', NULL, NULL, 'romain.berehouc@keon-group.com', NULL),
('2024-11-13', 'P-Op6', 'cloturee', 'Statut des capteurs', 'NASKEO', 'STJU', 'points_vigilance', 'EXPLOITATION', NULL, 'J''ai constaté sur le site de STJU que les exploitants ont la possibilité de simuler indéfiniment les capteurs de sécurité LSHH qui sont censé prévenir des risque de moussage/débordement de cuve. J', 'oui', 'Le compte exploitant a accès au mode simulation des capteurs sécu', 'Je propose de donner la possibilité à l''exploitant de simuler ces capteurs sécu sur une durée limitée. (temps écoulée remise en auto mode normale du capteur)
De ce fait, en cas de débordement de cuve le constructeur ne pourra pas être tenu responsable. Ou du moins nous n''aurons pas donnée l''autorisation à l''exploitant de shunter indéfiniment ce capteur', 'Modif autom'' après concertation', NULL, NULL, NULL, NULL),
('2024-11-13', 'P-Op6', 'cloturee', 'Débordement digestat', 'DOLE', 'DOLE', 'nc_qualite', 'EXPLOITATION', NULL, 'Débordement de digestat par le bol (A2TRE30)', 'oui', 'Mauvaise gestion de l''automate', 'Faire attention lors de l''incorporation', 'Modification des alarmes de l''automate pour mieux comprendre les symptômes et les gêrer', NULL, NULL, NULL, NULL),
('2023-11-10', 'P-Op2', 'cloturee', 'Surcout CAPEX et OPEX SPV', 'TERGREEN', 'ROMA - OUZO', 'nc_qualite', 'DEVELOPPEMENT', 'Ter''Green', 'De gros surcoûts de CAPEX et d''OPEX ont été identifiés après l''entrée de Ter''Green dans la SPV. A priori, ces surcoûts auraient pu être détectés en amont du closing.', 'oui', 'BP faits dans la précipitation
Absence de validation ou révision partielle', '1- Révision globale du projet (conception + mode de financement) pour retrouver des ratios acceptables', '1- Modification du master BP pour limiter les risques d''oubli de lignes de coûts
2- Ajout de commentaires pour alerter le développeur
3- Mise en place de revues de BP entre le développeur et son responsable', NULL, NULL, 'sophie.clermont@ter-green.com', NULL),
('2023-10-17', 'P-Op4', 'cloturee', 'Accident grue', 'NASKEO', 'AURO', 'incident_site', 'CONSTRUCTION', NULL, 'Il y''a eu un quasi-accident sur le chantier. La grue a reculé dans la nacelle entrainant des dégâts importants sur la nacelle et heureusement pas de blessures.', NULL, 'Pas d''organisation hiérarchique suffisamment claire sur le chantier. Pas de points sécurité suffisamment fréquents. Les zones de travaux statiques ne sont pas suffisamment balisées. Pas de kits tout faits pour les travaux en hauteur', '1. Mettre en place une organisation hiérarchique plus claire.
2. Mettre en place des ponts de sécurité réguliers 
3. Baliser les zones de travaux statiques
4. Mettre en place des kits pour travaux en hauteurs', '1. Mettre en place une organisation hiérarchique plus claire.
2. Mettre en place des ponts de sécurité réguliers 
3. Baliser les zones de travaux statiques
4. Mettre en place des kits pour travaux en hauteurs', NULL, NULL, NULL, NULL),
('2023-08-27', 'P-Op5', 'cloturee', 'Astreinte', 'SYCOMORE', 'NASK', 'nc_qualite', 'EXPLOITATION', NULL, '1. Retard dans le traitement des tickets des demandes clients quand ils appellent l''astreinte
2. Défaut dans le paramétrage de Swift
3. Diagnostic initial pas suffisamment technique', NULL, '1. Manque d''organisation interne, manque de disponibilité interne
2. Voir BLU
3. Pas de référent technique', '1. Faire un point sur les tickets non traités
2. BLU forme SGO au paramétrage de Swift
3. Définir un référent technique/recrutement', '3. Définir un référent technique/recrutement', NULL, NULL, NULL, NULL),
('2025-03-31', 'P-Op5', 'cloturee', 'quantité réceptionnée ne correspondant pas à celle sur le BL', 'SYCOMORE', 'PSTOC', 'nc_fournisseur', 'PIECES', 'vogelsang', '3 PIECES RECUES SUR 5 ', 'non', 'ERREUR DE PREPARATION FOURNISSEUR', 'RECLAMATION FOURNISSEUR / DEJA FAIT', 'CONTINUER LE CONTROLE A RECEPTION', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-03-24', 'P-Op5', 'cloturee', 'MACHINE HS APRES 6 MOIS D''UTILISATION', 'SYCOMORE', 'GEYS', 'nc_fournisseur', 'PIECES', 'MEDICAL DOMICILE', 'Le concentrateur d''oxygène a fumé et est en défaut d''allumage après seulement 6 mois d''utilisation

', 'oui', 'appareil de faible qualité. peut être sous dimensionné par rapport à son utilisation.', 'réclamation fournisseur à faire : faite le 27/03
remplacement de la machine si garantie sinon vente d''un nouvel équipement
remplacement standard de la machine en garantie par fournisseur.', NULL, NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-03-27', 'P-Op5', 'cloturee', 'marchandise commandée neuve , reçue reconditionnée', 'SYCOMORE', 'PSTOC', 'nc_fournisseur', 'PIECES', 'vogelsang', 'marchandise commandée neuve , reçue reconditionnée
réclamation fournisseur faite le 27/03/25', 'non', 'erreur de prépa fournisseur', 'continuer le contrôle qualité à réception de pièces.', NULL, NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-04-11', 'P-Op5', 'cloturee', 'ERREUR DE PREPA FOURNISSEUR', 'SYCOMORE', 'PPOIR', 'nc_fournisseur', 'PIECES', 'BORGER', 'LE FOURNISSEUR A FAIT UNE INVERSION DE PRODUIT DANS SA PREPAPARATION DE COMMANDE', 'non', 'ERREUR PREPA FOUR', 'RECLAMATION / FAIT
RECEPTION PIECE CONFORME / EN ATTENTE 
EXPEDITION MAUVAISE PIECE/ EN ATTENTE', 'CONTINUER CONTROLE A RECEPTION', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-04-14', 'P-Op5', 'cloturee', 'Absence fiche échantillons sous traitant AUREA', 'SYCOMORE', 'OUZO', 'nc_fournisseur', 'LABORATOIRE', 'AUREA', 'Pour limiter les aller/retour glacière, certains clients s''équipent de glacière AUREA qui sont conservées sur site. Lorsque des échantillons sont envoyés en analyses, il est indispensable d''inclure à la glacière une fiche échantillon avec les analyses à effectuer. Le laboratoire se charge d''éditer ces fiches, de les envoyer au client pour qu''elles soient ajouter à la glacière au moment de l''envoi. Lors du dernier envoi du site les 3 Dômes, une fiche sur 2 avait été ajoutée à la glacière. A la réception, AUREA a donc contacté le laboratoire pour qu''elle puisse être fournie.', 'oui', 'Problème d''inattention ', 'A l''envoi des fiches échantillons, appeler le client pour lui expliquer la démarche en lui précisant le nombre de fiches à imprimer.', 'Doubler le mail par un appel téléphonique', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-04-14', 'P-Op5', 'cloturee', 'Perte échantillon pendant un transport (Casse ou ouverture de flacons)', 'SYCOMORE', 'NASK', 'points_vigilance', 'LABORATOIRE', 'AUREA', 'Lors d''un transport de glacière du site de AUNIS BIOGAZ vers AUREA, un flacon PEHD s''est ouvert malgré la présence d''un opercule. L''échantillon s''est déversé dans la glacière entrainant une perte de volume et l''impossibilité de réaliser l''ensemble des analyses demandées. Il a donc été nécessaire de faire un renvoi de glacière pour une nouvelle prise d''échantillons.', 'oui', 'Soit le flacon a mal été refermé au moment de l''échantillonnage soit la glacière a été malmenée durant le transport entraînant l''ouverture d''un flacon.
Les glacières sont pourtant équipées de cales en mousse, ce qui laisse penser qu''il s''agit plutôt d''un manque de vigilance à la fermeture du flacon. Le problème peut être aussi dû à un manque d''honnêteté du sous traitant qui au moment de l''ouverture de la glacière a fait tomber le flacon...', 'Renvoyer 2 flacons pour que 2 nouveaux prélèvements soient réalisés et renvoyés en analyses.', 'Dans la mesure du possible, doubler le nombre de flacons prélevés pour qu''en cas d''ouverture de l''un d''entre eux il y en est un autre exploitable pour la réalisation de l''ensemble des analyses.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-04-14', 'P-Op5', 'cloturee', 'Pas de DAC de la part du chauffeur pour des SPAn', 'DOLE', 'GDOLE', 'nc_qualite', 'EXPLOITATION', 'EUROSERUM', 'Sans le DAC pour une livraison d''un gisement SPAn pas possible d''accepter le camion par l''exploitant', 'oui', 'Oubli du fournisseur après demande du chargé d''affaires TEIKEI', 'Appeler en urgence le CA TEIKEI et/ou joindre le fournisseur pour le recevoir par mail', 'Insister et communiquer une procédure de réception et d''acceptation des sites', NULL, NULL, 'anne.rivron@teikei.fr', 'damien.vacheret@sycomore-services.com'),
('2025-04-30', 'P-Sup2', 'cloturee', 'Non remise du livret d''accueil sécurité aux nouveaux arrivants', 'KEON', 'SKEON', 'nc_qualite', 'RH', NULL, 'Certains nouveaux arrivant n''ont pas reçu le livret sécurité à leur arrivée.', 'oui', NULL, 'transmission à All User du livret d''accueil sécurité pour s''assurer que chacun l''ai bien eu.', 'Le transmettre automatique à chaque arrivée.
=> CBO vérifie auprès de Maria', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-05-02', 'P-Sup4', 'cloturee', 'Hameçonnage et fraude au RIB', 'KEON', 'SNASK', 'points_vigilance', 'COMPATIBILITE', NULL, 'Un pirate informatique a réussi à nous envoyer une fausse facture d''un fournisseur existant, en reproduisant la plupart des informations de ce fournisseur, et en changeant le RIB. Le changement de RIB n''a pas été validé par téléphone et nous avons payé 6k€ sur le RIB frauduleux. Une plainte a été déposée', 'oui', 'Absence de vérification du changement de RIB avec l''interlocuteur habituel, par téléphone', 'La procédure comptable a été modifiée pour exiger systématiquement une validation téléphonique en cas de demande de changement de RIB
Une plainte a été déposée, et une demande de remboursement effectuée à la banque', 'La procédure comptable a été modifiée pour exiger systématiquement une validation téléphonique en cas de demande de changement de RIB', NULL, NULL, 'patrick.foltzenlogel@keon-group.com', 'corinne.beutier@keon-group.com'),
('2025-01-10', 'P-Sup1', 'cloturee', 'PV - Intégrer les PV des audits au tableau de gestion des NC', 'KEON', '2024', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', '1- Absence de formalisme de suivi des PV relevés pdt les Audit', NULL, 'Ne pas avoir pris le temps de les formaliser', 'Prendre le temps de les intégrer au tableau de gestion des NC', NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2023-12-07', 'P-Sup1', 'cloturee', 'PV - Evaluation satisfaction client 2023', 'NASKEO', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'L’évaluation de la satisfaction client 2023 n’a pas été réalisée pour le processus P3 – Réalisation
des prestation labo. Cela ne fait pas l’objet d’une NC dans la mesure où une action est planifiée
avec un objectif de réalisation en 2024 ', NULL, NULL, NULL, NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2023-12-07', 'P-Sup1', 'cloturee', 'PV - Plan de controle des pilotes', 'KEON', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'Les pilotes du processus P3 ne se sont pas totalement approprié le plan de contrôle établi (les
objectifs et cibles sont à définir)', NULL, NULL, NULL, NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2023-12-07', 'P-Sup1', 'cloturee', 'PV - Evaluation fournisseur', 'KEON', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'L’évaluation des sous-traitants et fournisseurs n’a pas été réalisée en 2023. Cela ne fait pas l’objet
d’une NC dans la mesure où une action est planifiée avec un objectif de réalisation en 2024
', NULL, NULL, NULL, NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL);
