INSERT INTO public._nc_staging VALUES
('2023-12-07', 'P-Sup1', 'cloturee', 'PV - peu de remontée de NC', 'KEON', '2023', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'Peu de remontée des réclamations sur la période d’absence du Responsable Qualité. Relance en
Septembre 2023 à la prise de poste de Florence (à surveiller lors du prochain audit)
', NULL, NULL, NULL, NULL, NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2025-05-02', 'P-Op5', 'cloturee', 'Non livraison de Metamix sur CERES comme prévu. Le transporteur n''a pas informé', 'TEIKEI', NULL, 'nc_fournisseur', 'ACHAT', NULL, 'La non livraison a entrainé une baisse de la production de gaz de 100Nm3/h sur la journée de Dimanche 04/05/2025', 'oui', 'Fiabilité transporteur', 'Appel au fournisseur pour rappel des règles de prévenances en cas de problème au chargement', NULL, NULL, NULL, 'olivier.mathieu@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-05-12', 'P-Op5', 'cloturee', 'Non Livraison sur CERES de METAMIX pour la deuxième fois consécutive', 'SYCOMORE', NULL, 'nc_fournisseur', 'EXPLOITATION', NULL, 'La livraison prévue Vendredi 09/05/2025, n''a pas été effectuée, cas identique au 02/05/2025', NULL, NULL, NULL, NULL, NULL, NULL, 'olivier.mathieu@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-05-27', 'P-Op1', 'cloturee', 'Non précision d''une donnée sur l''évolution du projet négociée avec le client', 'NASKEO', 'MAR2', 'points_vigilance', 'COMMERCE', NULL, 'Non précision d''une donnée sur l''évolution du projet négociée avec le client : négociation de la cuve maturation en future doublon de la cuve de méthanisation en phase commerciale / information non transmise par le commerce à la réa (pourtant une réunion de passation a eu lieu et ce sujet avait été abordé avec le seul commercial présent Jérémy) / le client nous a averti de cela une fois les plans finis et le chantier (VRD et GC) commencé / il a fallu tout remodifier à la dernière minute et faire une solution d''appoint : impact sur les serpentins et les thermaflex avec une perte de marge et de capacité de négo, ajout d''inserts pour le refoulement Premix et cuve lisier (les cuves étant déjà à moitié coulées, nous avons dû adapter les positions en conséquence et les mettre plus haut que nécessaire), d''un point de vue global nous aurions pu implanter différemment la cuve maturation et optimiser les couts et l''exploitation future (linéaires de cana...) + annulation de commande à la dernière minute, ce qui engendre une perte de crédibilité + reprise des plans, NDC et cout RH ', 'oui', 'Il y eu un manque de communication/oubli d''information côté commercial malgré la réunion de passation et les demandes (mails) de l''EXE pour une clarification de la fonctionnalité/évolutivité de cette cuve de maturation ', 'Les actions sur le court terme ont été mises en œuvre en urgence par l''EXE et la REA ', 'Etre plus assidu sur la préparation de la réunion de passation, qui a son importance
Améliorer la maîtrise des projets côté commerce', NULL, NULL, 'camille.gregoire@naskeo.com', 'germain.lheriau@naskeo.com'),
('2025-05-29', 'P-Sup4', 'cloturee', 'Ouverture d''un ticket mardi car panne d''accès au réseau à Nantes. Aucune action avant relance par VBE et demande d''ouverture d''un ticket chez Nirwana', 'KEON', 'SKEON', 'nc_qualite', 'SERVICES GENERAUX', NULL, 'Ouverture d''un ticket mardi car panne d''accès au réseau à Nantes. Aucune action car le technicien pensait que c''était lié au travaux. Hors aucun travaux nimpactait le réseau. Après relance directe le mercredi par VBE. Ouverture d''un ticket chez Nirwana et dépannage sous 15 min.', 'oui', 'Pas de prise en compte du ticket 
Pas de rappel de la personne ayant ouvert le ticket. 
Pas d''actions engagées sur la base de supposition.', 'Action corrective le lendemain avec ouverture d''un ticket chez Nirwana et traitement immédiat.', 'Écrire la procédure de traitement des ticket avec engagements de délais ', NULL, NULL, 'valentin.bertrand@sycomore-services.com', 'valentin.bertrand@sycomore-services.com'),
('2025-05-23', 'P-Op6', 'cloturee', 'Réserve incendie non remplie', 'CERES', 'CERES', 'points_vigilance', 'EXPLOITATION', NULL, 'la réserve incendie de CERES n''est pas remplie', 'oui', 'exploitation et production gaz prioritaire par rapport à ce sujet.', '1- Remplir la réserve incendie
2- Vérifier l''absence de fuite', '1- procédure de remplissage => Fait par FMS', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Alexandre.Piton@keon-group.com'),
('2025-06-13', 'P-Op6', 'cloturee', 'Camion de pulpe de tomate livré Vendredi 13/06 et non prévu au planning. A posé un problème de gestion des liquides sur site car pas de possibilité de le stocker.', 'TEIKEI', NULL, 'nc_fournisseur', 'ACHAT', NULL, 'Camion de pulpe de tomate livré Vendredi 13/06 et non prévu au planning. A posé un problème de gestion des liquides sur site car pas de possibilité de le stocker.', NULL, NULL, 'Rappel aux fournisseurs et transporteurs des règles au moment des plannings suivant (par téléphone)', NULL, NULL, NULL, 'Alexandre.Piton@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-06-07', 'P-Op6', 'cloturee', 'Casse d''un couteau du à indésirables dans matières stercoraires.', 'TEIKEI', NULL, 'nc_fournisseur', 'ACHAT', NULL, 'Casse d''un couteau du à indésirables dans matières stercoraires.', NULL, NULL, 'Exceptionnel, remontée faite au fournisseur pour information à l''usine. ', NULL, NULL, NULL, 'Alexandre.Piton@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-06-18', 'P-Op6', 'cloturee', 'Transport arrivée sans information', 'TEIKEI', NULL, 'nc_fournisseur', 'ACHAT', NULL, 'Camion de graisse de phytorestore arrivé sans information aux alentours de 11h, sans être prévu au planning. Impossible de le prendre en charge car cuve pleine et pompe de vidange en panne. TH sont revenues à 14h. TH m''a recontacté indiquant que Phytorestore avait l''info que la pompe serait réparée. . Information non communiquée par le groupe. TH est donc retourné avec la matière. Pour info TH indique que phytoresore voulait absolument vider chez nous car nous sommes "les moins chers". ', NULL, NULL, NULL, NULL, NULL, NULL, 'Alexandre.Piton@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-07-02', 'P-Op6', 'cloturee', 'Décalage planning Methamix du 30/06 au 01/07', 'TEIKEI', NULL, 'nc_fournisseur', 'EXPLOITATION', NULL, 'Décalage de planning arrivée de Méthamix du 30/06 au 01/07 obligeant l''incorpo trop rapide du Méthamix et une augmentation du FOS/TAC dans digesteur G1 (impliquant un arrêt d''alimentation).', NULL, NULL, 'Problème au chargement. Rappel des règles de prévenance. ', 'Changement de transporteur.', NULL, NULL, 'Alexandre.Piton@keon-group.com', 'gwenaelle.jacq@teikei.fr'),
('2025-05-21', 'P-Op5', 'cloturee', 'Perte d''échantillons sous-traitant', 'SYCOMORE', 'OUZO', 'nc_fournisseur', 'LABORATOIRE', 'AUREA', 'Envoi d''un digestat solide et d''un digestat liquide le 15/05/2025. Preuve de réception le 16/05 de la part de TNT. La glacière vide est bien revenue d''AUREA vers le Laboratoire.', 'oui', 'Après un mois de recherche, les échantillons ont bien été retrouvés. Le responsable commercial d''AUREA nous a retrouvé car il est remonté à nous par le biais de l''adresse d''envoi de chez OUZO. A priori, absence des fiches échantillons dans le colis, ce qui a mis en difficulté le sous traitant pour retrouver nos échantillons... ', 'Vérifier le bon enregistrement des échantillons sur la plateforme après envoi pour agir vite en cas de problème et retrouver plus facilement les échantillons.', 'Insister auprès des exploitants sur l''importance de mettre ces fiches échantillons dans les glacières. Le soucis ne se pose pas dans la majeure partie des cas car ces fiches sont introduites dans les glacières par nous au moment de l''expédition des flaconnages. Afin d''éviter que ces fiches soient retirées au moment de la préparation des échantillons, nous les bloquons entre le cale flacons et la glacière. L''exploitant n''a donc plus besoin de les retirer pour préparer ces échantillons. Il ne peut donc plus oublier de les ajouter avant envoi. Les sites équipés de glacière tels que ABEV, GATD et OUZO devront toujours imprimer et ajouter ces fiches dans les glacières. Avantage de disposer d''une glacière sur site : éviter un transport et être plus réactif en cas d''analyses urgentes.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-05-19', 'P-Op5', 'cloturee', '1 échantillon sur 3 traités en sous traitance', 'SYCOMORE', 'GATD', 'nc_fournisseur', 'LABORATOIRE', 'AUREA', '3 échantillons (6 flacons au total, 2 flacons de 1 Litre par échantillon) ont été envoyés chez AUREA pour l''analyse des Inertes. Un seul rapport réceptionné le 19/05 pour une réception le 06/05.', 'oui', 'Nous pensons que les flacons n''ont pas été nommés par l''exploitant. A la réception, un seul échantillon a donc été enregistré au lieu de 3. La commande sur la plateforme indiquait cependant 3 analyses. Le sous traitant aurait donc pu contacter le Laboratoire pour comprendre pourquoi il y avait un seul échantillon au lieu de 3.', 'Sur le court terme, rien n''a pu être fait sur cette réception car nous nous sommes rendus compte trop trad qu''un seul échantillon avait été traité (au moment de la réception du rapport). Les 6 flacons avaient été mélangés et homogénéiser pour réaliser l''analyse d''inertes.', 'Vérifier à chaque envoi d''analyses en sous traitance que tous les échantillons ont bien été réceptionnés. Ceci permettra d''agir plus vite et de régler le problème le plus tôt possible.', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-06-04', 'P-Op5', 'cloturee', 'Problème homogénéité échantillon envoyé en sous traitance', 'SYCOMORE', 'LGATD', 'nc_fournisseur', 'LABORATOIRE', 'AUREA', 'Envoi d''une FRC d''AUREA comme quoi 2 flacons identifiés "Soupe 1" différents. Nous avons donc demandé de mélanger les deux et de faire l''analyse sur le mélange. Au 11/07 toujours pas de rapport et aucun retour sur cette analyse.', 'oui', 'L''exploitant au moment de l''échantillonnage ne s''est pas rendu compte que les deux prélèvements étaient d''un aspect bien différents. A la réception, le laboratoire sous traitant a jugé utile de nous prévenir mais n''a certainement jamais pris en compte notre retour.', 'Demander aux exploitants de faire attention au moment de la préparation des échantillons.', 'Faire un point avec le sous traitant sur le fait de ne jamais avoir de retour concernant l''absence de rapport...', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-05-28', 'P-Op5', 'cloturee', 'Une analyse manquante sur un envoi en sous traitance', 'SYCOMORE', 'ABEV', 'nc_fournisseur', 'LABORATOIRE', 'AUREA', 'Une glacière contenant 1 échantillon de digestat solide et un échantillon de digestat liquide a été envoyée du site de ABEV vers AUREA pour des analyses en DIGAGRI. Au 11/07, pas de rapport d''inertes sur le digestat solide alors que tout a été fait sur le reste des échantillons.', 'oui', 'Etant donné que je n''ai eu aucun retour à ce jour de notre sous traitant, je suppose que l''échantillon a été perdu ou qu''il n''y avait pas suffisamment de volume pour mener à bien cette analyse.', 'Relance du fournisseur', 'Pour le moment, aucune action n''est envisagée car pas de réponse du sous traitant à nos interrogations...', NULL, NULL, 'emilie.huline@sycomore-services.com', 'emilie.huline@sycomore-services.com'),
('2025-07-17', 'P-Op3', 'cloturee', 'Emprise merlon (implantation)', 'NASKEO', 'RUIS', 'nc_qualite', 'BUREAU D''ETUDES MOE/ETD', NULL, 'La parcelle de RUIS est en pente, GMO n''est pas formé sur Geomensura qui permet de dessiner l''emprise réelle des merlons. En réalité le merlon dépasse de la limite de propriété. Conséquence ; reprise d''études au démarrage du chantier et perturbation du planning. ', 'oui', '- Pas de formation géomensura
- Pas d''alerte du terrassier au moment des consultations', '- Travail avec ingé MOE (CBE) + terrassier pour reprendre l''implantation (une cuve a été déplacée). Impact finalement mineur sur le planning.
==> OK
', '1- Ajout dans listing question à poser aux entreprises de demander au terrassier de valider l''implantation des merlons.
=> OK
2- Demande de devis pour formation geomensura 
=> En cours
3- Réaliser la formation Géomensura', NULL, NULL, 'marion.pavat@naskeo.com', 'marion.pavat@naskeo.com'),
('2025-07-25', 'P-Op3', 'cloturee', 'Gestion de l''eau : puits d''infiltration', 'NASKEO', 'RUIS', 'points_vigilance', 'BUREAU D''ETUDES MOE/ETD', NULL, 'Gestion de l''eau : dans dossier ICPE la gestion des eaux propres se faisait par un bassin d''infiltration. Par manque de place en MOE nous sommes passés sur des puits d''infiltration (en pensant que ce serait équivalent pour l''administration). Or nous apprenons au démarrage du chantier que c''est interdit dans cette région (interdiction non stricte). ', 'oui', 'Pas de validation demandée au BE règlementaire avant de prendre la décision de passer sur des puits d''infiltration au lieu d''un bassin d''infiltration.', 'Communication auprès du BE 
Proposition de l''IMOE : petit bassin d''infiltration avant les puits qui pourra plus facilement être isolé en cas de pollution.
==> OK', 'Demander validation auprès du BE règlementaire à chaque changement dans la gestion des eaux par rapport au dossier ICPE
==> OK ajouté dans processus interne', NULL, NULL, 'marion.pavat@naskeo.com', 'marion.pavat@naskeo.com'),
('2025-07-25', 'P-Sup1', 'cloturee', 'Refonte des processus', 'KEON', 'KEON', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', NULL, 'développement du groupe nécessitant une réorganisation des métiers', 'non_concerne', 'Création de Teikei', 'création de la cartographie des processus', 'Création des loggigramme par processus', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-07-25', 'P-Sup1', 'cloturee', 'Intégration de TEIKEI dans l''ISO', 'TEIKEI', 'KEON', 'axe_amelioration', 'APPROVISIONNEMENT', NULL, 'création de Teikei', NULL, 'Création de Teikei', 'faire le point sur les métiers de Teikei', 'Créer les logigrammes des processus associés', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-07-25', 'P-Sup1', 'cloturee', 'Intégrer la qualité et la sécurité au On boarding', 'KEON', 'KEON', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', NULL, 'certain collaborateur ne sont pas informer sur la politique qualité Sécurité du groupe', NULL, NULL, NULL, '1- Envoyer une tache à RQSE a chaque arrivée', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-07-25', 'P-Op5', 'cloturee', 'Organisation Labo', 'SYCOMORE', NULL, 'axe_amelioration', 'LABORATOIRE', NULL, 'Mettre en place une organisation durable pour la sous-traitance', NULL, NULL, NULL, 'Optimiser la sous-traitance face au volume d''annalyse', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'emilie.huline@sycomore-services.com'),
('2025-07-25', 'P-Op4', 'cloturee', 'Master test à chaud', 'NASKEO', NULL, 'axe_amelioration', 'MISE EN SERVICE', NULL, 'suivi est traçabilité des test à chaud', NULL, NULL, NULL, '- Réaliser une check list ou master complet pour valider les test à chaud', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'pierre.labrunie@naskeo.com'),
('2025-07-25', 'P-Sup2', 'cloturee', 'LUCCA', 'KEON', 'KEON', 'axe_amelioration', 'RH', NULL, 'changement SIRH pour remplacer Eurécia', NULL, NULL, NULL, 'Mettre en place LUCCA', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-07-25', 'P-Sup2', 'cloturee', 'EPI - entretient Annuel', 'KEON', 'KEON', 'axe_amelioration', 'RH', NULL, 'certains collaborateur n''ont pas d''EPI', NULL, NULL, NULL, 'Intégrer la validation des EPI lors des Entretients annuel', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'camille.bolo@keon-group.com'),
('2025-07-25', 'P-Sup5', 'cloturee', 'Evaluation fournisseurs', 'KEON', 'KEON', 'axe_amelioration', 'ACHAT', NULL, 'Le choix des fournisseurs a évaluer doit etre préciser', NULL, NULL, NULL, 'mettre en cohérence l''alignement du CA par rapport à l''année de l''évaluation', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'alexandre.baffou@naskeo.com'),
('2025-07-25', 'P-Sup5', 'cloturee', 'E-Attestation', 'KEON', 'KEON', 'axe_amelioration', 'ACHAT', NULL, 'Récolter la documentation légale
Obligation en cas de controle pour éviter le travail illégal', NULL, NULL, NULL, 'Mise en place de e-Attestation pour 200 fournisseurs (CA sup à 5000€)', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'alexandre.baffou@naskeo.com'),
('2025-07-25', 'P-Sup4', 'cloturee', 'Divalto', 'KEON', NULL, 'points_vigilance', 'SERVEUR-INFORMATIQUE-WEB', NULL, 'Lenteur divalto
Tenir compte des difficultés quotidiennes des opérateurs', NULL, 'Problème de paramétrage des notifications DIVALTO', 'Suppression des notifications + redémarrage automatique du serveur DIVALTO toutes les nuits : fait le 25/07/2025', 'Amélioration de l''ERP : montée de version et correction des bugs', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'hugues.molto@keon-group.com'),
('2025-07-25', 'P-Sup4', 'cloturee', 'ERP SPV', 'KEON', NULL, 'axe_amelioration', 'SERVEUR-INFORMATIQUE-WEB', NULL, 'deploiement ERP SPV (gestion)', NULL, NULL, NULL, 'Avoir un outil de pilotage des SPV
Obtenir une base de données.
=> gagner en performance', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'valentin.bertrand@sycomore-services.com'),
('2025-08-19', 'P-Op5', 'cloturee', 'Satisfaction client Labo', 'SYCOMORE', 'KEON', 'axe_amelioration', 'LABORATOIRE', NULL, 'absence d''évaluation de la satisfaction client coté labo!', NULL, NULL, NULL, 'Mettre en place un formulaire d''ici 2026', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'emilie.huline@sycomore-services.com'),
('2025-09-11', 'P-Sup5', 'cloturee', 'PV3. Processus non complet', 'KEON', '2025', 'points_vigilance', 'COMPATIBILITE', 'Audit interne ISO', 'le processus n''est pas a jour', NULL, 'La description du processus appel les remarques suivantes :
-	Les activités gestion de trésorerie et frais de déplacement ne sont pas intégrées dans le processus, 
-	Des activités antérieures à la commande sont intégrées au processus alors qu’elles font partie du processus Ventes 
-	Les activités Bon à Payer sur la compta fournisseurs ne sont pas intégrées dans la description du processus
', NULL, 'reprendre le processus compta afin de le compléter:
- Note de frais => fait
- Trésorerie  (pas d''interet)
- cloture => Fait', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'corinne.beutier@keon-group.com'),
('2025-09-23', 'P-Op5', 'cloturee', 'Erreur de référence', 'SYCOMORE', 'DOUE', 'nc_qualite', 'MAINTENANCE', NULL, 'Suite à un dépannage téléphonique, le client nous as fait une demande pour intervenir sur son site avec un kit de pièces. Nous lui avons fournir le mauvais jeu de pièces.
', 'oui', NULL, 'Un technicien est venu chercher les bonnes pièces au stock et est reparti sur site faire l''intervention', 'Demander au client la plaque signalétique pour s''assurer du bon modèle des pièces prévues.', NULL, NULL, 'Sylvain.Antz@naskeo.com', 'Sylvain.Antz@naskeo.com'),
('2025-10-02', 'P-Op4', 'cloturee', 'Avoir une continuité dans les indices', 'NASKEO', '2025', 'axe_amelioration', 'EXECUTION', 'Audit interne ISO', 'reprise à l''indice 0 lors de la passation en réalisation. il faut donc y avoir deux versions A  source d''erreur.', NULL, 'Il est noté une différence d’indice entre la spécification PID indice D et le tableau de suivi des livrables qui est à l’indice B', NULL, 'Reprise à Zéro, indice "0" après passation .
Si reprise a zéro d''un document déja existant alors faire une modification du nommage complet du document', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'betty.walheim@naskeo.com'),
('2025-10-03', 'P-Op5', 'cloturee', 'Erreur de livraison transporteur = retard de livraison client.', 'SYCOMORE', 'PHAGU', 'nc_fournisseur', 'PIECES', NULL, 'le transporteur s''est trompé d''adresse de destination ce qui a engendré une relivraison et donc un retard de livraison pour le client', 'non', NULL, NULL, 'contrôle et suivi courant des informations partagées.', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-10-03', 'P-Sup2', 'cloturee', 'manque fiche de poste de Virgile ICONC', 'NASKEO', '2025', 'axe_amelioration', 'COMMERCE', 'Audit interne ISO', 'absence de fiche de poste', NULL, NULL, NULL, 'rédiger la fiche de poste de virgile pour le poste ICONC', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'germain.lheriau@naskeo.com'),
('2025-10-07', 'P-Sup6', 'cloturee', 'REX projet abandonné', 'KEON', '2025', 'axe_amelioration', 'R&D', 'Audit interne ISO', 'Un REX formel pourrait être réalisé sur les projets abandonnés pour en identifier les causes et mettre en œuvre des actions correctives.', NULL, NULL, 'Réalisation d''une note sur le REX projet "FLEXIMIX"  et les axes d''amélioration', 'Validation +++ lors de la présentation. 

+ actions en fonction du REX qui sera produit.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'manon.mangin@keon-group.com'),
('2025-10-07', 'P-Sup3', 'cloturee', 'Réception Salon', 'KEON', '2025', 'axe_amelioration', 'COMMUNICATION - MARKETING', 'Audit interne ISO', 'La réception de la prestation de FG design (prestataire de salon) pourrait être formellement établie', NULL, NULL, NULL, 'Mise en place d''un  PV de réception de salon', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'claire.sassias@keon-group.com'),
('2025-10-07', 'P-Sup4', 'cloturee', 'PV2. suivi des actions - en retard souvent', 'KEON', '2025', 'points_vigilance', 'SERVEUR-INFORMATIQUE-WEB', 'Audit interne ISO', 'Le plan d’actions du processus laisse apparaitre de nombreux cas en retard qui demandent une action (ex ; nommage des documents)', NULL, NULL, '1. faire le ménage dans les actions
2.  indiqué une date réévaluée pour générer une nouvelle alerte.', 'mieux anticiper les taches a réaliser', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'valentin.bertrand@sycomore-services.com'),
('2025-10-07', 'P-Op6', 'cloturee', 'PV7. documents audit non présenté', 'KEON', '2025', 'points_vigilance', 'EXPLOITATION', 'Audit interne ISO', 'Les enregistrements suivants n’ont pu être fournis lors de l’audit :
-	Contrôle électrique 3 Dômes
-	Rondes 3 Dômes pour la maintenance 
-	Maintenance périodique des agitateurs et de l’épuration', NULL, NULL, NULL, 'documents à fournir à l''auditeur', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Pascal.kozerawski@keon-group.com'),
('2025-10-07', 'P-Sup1', 'cloturee', 'MaJ manuel Qualité', 'KEON', '2025', 'axe_amelioration', 'QUALITE - ISO - QUALIMETHA', 'Audit interne ISO', 'Les valeur PRIDE décrites dans le MQ ne sont plus d’actualité et demandent à être actualisées.

La documentation des processus appelle les remarques suivantes :
-	La cartographie des processus n’identifie pas les acteurs et les responsabilités tel que défini dans le MQ
-	Le lien entre les processus et procédures pourrait être formellement établi 
', NULL, NULL, NULL, 'mettre à jour le manuel qualité', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-09-23', 'P-Op6', 'cloturee', 'Incendie stockage matière', 'LES 3 DOMES', 'OUZO', 'incident_site', 'EXPLOITATION', NULL, 'autoinflammation', NULL, NULL, NULL, 'suivi de la température des stockages', NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2025-10-14', 'P-Sup4', 'cloturee', 'Piratage boite mail FHA', 'KEON', NULL, 'nc_qualite', 'SERVEUR-INFORMATIQUE-WEB', NULL, 'FHA c''est fait pirater sa boite mail! Avec envoi de devis avec lien Sign in', NULL, NULL, NULL, 'déterminer la cause', NULL, NULL, 'florence.martin-sisteron@naskeo.com', NULL),
('2025-10-22', 'P-Op5', 'cloturee', 'erreur référence livrée (fournisseur)', 'SYCOMORE', 'PAURO', 'nc_fournisseur', 'PIECES', 'lubexcel', 'Le fournisseur a livré la mauvaise ref au client .
', 'non_concerne', NULL, 'marchandise non conforme récupérée le 28/10/25
marchandise conforme livrée le 29/10/25', 'faire rappel au fournisseur', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-11-13', 'P-Sup1', 'cloturee', 'Logo organisme certificateur dans le manuel qualité', 'KEON', '2025', 'nc_qualite', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'présence d''un logo Afaq dans le manuel qualité.', NULL, 'utilisation d''un logo issu d''internet sans prêter attention à l''organisme certificateur indiquer sur le logo', 'enlever le logo Afaq. fait le 13/11/2025', 'mettre le logo DEKRA.
à faire avant fin 2025', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-11-13', 'P-Sup1', 'cloturee', 'Evaluation de l''efficacité des actions', 'KEON', '2025', 'points_vigilance', 'QUALITE - ISO - QUALIMETHA', 'ISO 9001', 'Manque l''évaluation des l''efficacités des actions', NULL, 'oubli de formalisation de l''exigence de la norme', 'modififier', 'modifier le formulaire en ajoutant une case "Efficacité"', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'florence.martin-sisteron@naskeo.com'),
('2025-11-19', 'P-Op5', 'cloturee', 'conditionnement à réception de stator C66', 'SYCOMORE', 'pstoc', 'nc_fournisseur', 'PIECES', 'vogelsang', 'à réception de la palette, conditionnement abimé et des rayures constatées sur les stators .
retour fournisseur en cours.
attente avoir.', 'non', 'N/C', 'N/C', 'N/C', NULL, NULL, 'Paul.Lapeyre@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-11-20', 'P-Sup2', 'cloturee', 'Suivi des visites médicales', 'KEON', '2025', 'nc_qualite', 'RH GROUPE', 'ISO 9001', 'Suivi du tableau non à jour', NULL, 'LUCCA ne permet pas une vue globale ainsi un report est nécessaire si on veut un global.', NULL, 'Mettre à jour le fichier de suivi. 
Voir si un report peut être automatisé.', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'audrey.kabore@keon-group.com'),
('2025-11-27', 'P-Op5', 'cloturee', 'validation du CR d''intervention', 'SYCOMORE', '2025', 'axe_amelioration', 'MAINTENANCE', 'ISO 9001', 'pas de formalisation de la validation', NULL, NULL, NULL, 'mettre en place une signature de validation sur le CR sur DOMMS', NULL, NULL, 'florence.martin-sisteron@naskeo.com', 'Sylvain.Antz@naskeo.com'),
('2025-12-05', 'P-Op5', 'cloturee', 'réception de la marchandise non cerclé, les pièces ce sont entrechoqués pendant le transport', 'SYCOMORE', 'PSTOC', 'nc_fournisseur', 'PIECES', 'VOGELSANG', 'pièces reçues rayées, litige en cours chez Dachser et Vogelsang', 'non', 'problème de conditionnement fournisseur', 'avoir reçu le 15 03/26', 'contrôle qualité à réception des marchandises', NULL, NULL, 'Paul.Lapeyre@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2025-12-15', 'P-Op5', 'cloturee', 'Materiel sous garantie ne fonctionnant plus correctement', 'SYCOMORE', 'DAMP', 'nc_qualite', 'PIECES', 'Almadia', 'Le 1 er concentrateur d''O2 est en défaut rouge et jaune allum tous le temps et bip sonore  

Le second reste en jaune(orange) même en diminuant le débit au minimum 
', 'ne_sais_pas', 'ne s''exprime pas', 'faire retour fournisseur pour remplacement standard ou réparation', 'ne s''exprime pas', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2026-01-23', 'P-Op5', 'cloturee', 'Non prise en compte de la totalité de la commande.', 'SYCOMORE', 'ABEV', 'nc_fournisseur', 'PIECES', 'vogelsang', 'Le fournisseur n''a pris qu''une page sur deux de notre commande en compte. 
il relivre dans les plus brefs délais le reliquat', 'ne_sais_pas', 'NSP', 'déclaration fournisseur : fait le 26/01/26
suivi du service du reliquat jusqu''à livraison', 'réclamer des ARC détaillés. c''est chose faite à mainte reprises.', NULL, NULL, 'nicolas.narolles@sycomore-services.com', 'nicolas.narolles@sycomore-services.com'),
('2026-01-26', 'P-Op5', 'cloturee', 'pièce manquante à la livraison du client', 'SYCOMORE', 'PFONT', 'nc_qualite', 'PIECES', NULL, 'manque de vigilance sur une commande, pièce manquante sur une commande', 'non', NULL, 'expedier la piece manquante , fait le 26/01/26', 'plus de vigilance', NULL, NULL, 'Paul.Lapeyre@sycomore-services.com', 'nicolas.narolles@sycomore-services.com');
